=== aaronweldy/espn-openapi/json_schemas/athlete_contract_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/AthleteContractSchema",
    "definitions": {
        "AthleteContractSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "birdStatus": {
                    "type": "integer"
                },
                "baseYearCompensation": {
                    "$ref": "#/definitions/Ion"
                },
                "poisonPillProvision": {
                    "$ref": "#/definitions/Ion"
                },
                "incomingTradeValue": {
                    "type": "integer"
                },
                "outgoingTradeValue": {
                    "type": "integer"
                },
                "minimumSalaryException": {
                    "type": "boolean"
                },
                "optionType": {
                    "type": "integer"
                },
                "salary": {
                    "type": "integer"
                },
                "salaryRemaining": {
                    "type": "integer"
                },
                "yearsRemaining": {
                    "type": "integer"
                },
                "season": {
                    "$ref": "#/definitions/Season"
                },
                "team": {
                    "$ref": "#/definitions/Season"
                },
                "tradeKicker": {
                    "$ref": "#/definitions/TradeKicker"
                },
                "tradeRestriction": {
                    "type": "boolean"
                },
                "unsignedForeignPick": {
                    "type": "boolean"
                },
                "active": {
                    "type": "boolean"
                }
            },
            "required": [
                "$ref",
                "active",
                "baseYearCompensation",
                "birdStatus",
                "incomingTradeValue",
                "minimumSalaryException",
                "optionType",
                "outgoingTradeValue",
                "poisonPillProvision",
                "salary",
                "salaryRemaining",
                "season",
                "team",
                "tradeKicker",
                "tradeRestriction",
                "unsignedForeignPick",
                "yearsRemaining"
            ],
            "title": "AthleteContractSchema"
        },
        "Ion": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "active": {
                    "type": "boolean"
                }
            },
            "required": [
                "active"
            ],
            "title": "Ion"
        },
        "Season": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Season"
        },
        "TradeKicker": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "percentage": {
                    "type": "number"
                },
                "value": {
                    "type": "integer"
                },
                "tradeValue": {
                    "type": "integer"
                }
            },
            "required": [
                "active",
                "percentage",
                "tradeValue",
                "value"
            ],
            "title": "TradeKicker"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/athlete_contract_nba_1966_2024.json
{"$ref":"http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/athletes/1966/contracts/2024?lang=en&region=us","birdStatus":0,"baseYearCompensation":{"active":false},"poisonPillProvision":{"active":false},"incomingTradeValue":47607350,"outgoingTradeValue":47607350,"minimumSalaryException":false,"optionType":0,"salary":47607350,"salaryRemaining":0,"yearsRemaining":2,"season":{"$ref":"http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/seasons/2024?lang=en&region=us"},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/seasons/2024/teams/13?lang=en&region=us"},"tradeKicker":{"active":false,"percentage":0.0,"value":0,"tradeValue":0},"tradeRestriction":true,"unsignedForeignPick":false,"active":true}
