=== aaronweldy/espn-openapi/json_schemas/athlete_contracts_list_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/AthleteContractsListSchema",
    "definitions": {
        "AthleteContractsListSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Item"
                    }
                }
            },
            "required": [
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "AthleteContractsListSchema"
        },
        "Item": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Item"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/team_athletes_soccer_eng.1_2024_team359.json
{
  "count": 35,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 2,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/138398?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/196176?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/341729?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/343573?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/390095?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/214794?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/217482?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/236322?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/238004?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/241077?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/277385?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/282716?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/298329?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/304965?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/351059?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/358436?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/392659?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/88274?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/165778?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/189972?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/203669?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/209581?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/238262?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/307172?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/athletes/349733?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/league_nfl_seasons.json
{
  "count": 104,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 5,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2025?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2022?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2020?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2019?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2018?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2017?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2016?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2015?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2014?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2013?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2012?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2011?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2010?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2009?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2008?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2007?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2006?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2005?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2004?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2003?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2002?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2001?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/league_nfl_events_week_1_season_2025.json
{
  "count": 272,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 11,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772510?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772714?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772830?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772829?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772719?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772720?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772718?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772721?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772827?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772828?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772832?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772831?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772722?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772723?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772918?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772810?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772936?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772725?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772834?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772835?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772724?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772728?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772833?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772727?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401772836?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/baseball_mlb_positions_processed.json
{
  "count": 23,
  "pageIndex": 1,
  "pageSize": 10,
  "pageCount": 3,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/0?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/1?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/2?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/3?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/4?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/5?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/6?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/7?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/8?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/positions/9?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/college_football_group_90_children.json
{"count":2,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/college-football/seasons/2025/types/2/groups/80?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/college-football/seasons/2025/types/2/groups/81?lang=en&region=us"}]}

=== aaronweldy/espn-openapi/json_output/hockey_nhl_positions_processed.json
{
  "count": 28,
  "pageIndex": 1,
  "pageSize": 10,
  "pageCount": 3,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/1?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/2?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/3?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/4?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/5?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/8?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/9?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/11?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/12?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/hockey/leagues/nhl/positions/13?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/soccer_uefa.champions_positions_processed.json
{
  "count": 42,
  "pageIndex": 1,
  "pageSize": 10,
  "pageCount": 5,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/1?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/2?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/3?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/4?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/5?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/6?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/7?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/8?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/9?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/soccer/leagues/uefa.champions/positions/10?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/athlete_contracts_nba_wembanyama.json
{
  "count": 3,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/athletes/5104157/contracts/2026?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/athletes/5104157/contracts/2025?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/athletes/5104157/contracts/2024?lang=en&region=us"
    }
  ]
}
