=== aaronweldy/espn-openapi/json_schemas/athlete_contracts_list_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/AthleteContractsListSchema",
    "definitions": {
        "AthleteContractsListSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Item"
                    }
                }
            },
            "required": [
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "AthleteContractsListSchema"
        },
        "Item": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Item"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/basketball_nba_positions_processed.json
{
  "count": 11,
  "pageIndex": 1,
  "pageSize": 10,
  "pageCount": 2,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/0?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/1?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/2?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/3?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/4?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/5?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/6?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/7?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/8?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/positions/9?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/nfl_providers_list.json
{"count":71,"pageIndex":1,"pageSize":25,"pageCount":3,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/0?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/1?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/2?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/3?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/4?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/5?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/6?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/7?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/8?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/9?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/10?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/11?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/12?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/13?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/14?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/15?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/16?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/17?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/18?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/19?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/20?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/21?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/22?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/23?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/providers/24?lang=en&region=us"}]}

=== aaronweldy/espn-openapi/json_output/league_nfl_calendar.json
{
  "count": 4,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/calendar/ondays?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/calendar/offdays?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/calendar/blacklist?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/calendar/whitelist?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/team_injuries_baseball_mlb_15.json
{
  "count": 13,
  "pageIndex": 1,
  "pageSize": 100,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/4722960/injuries/-153169?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/4917640/injuries/966375?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/5271396/injuries/966302?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/40981/injuries/-152264?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/40346/injuries/965649?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/37820/injuries/-148962?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/5133834/injuries/958633?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/5150962/injuries/-145272?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/33860/injuries/955861?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/5080750/injuries/-144181?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/31117/injuries/-143748?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/33760/injuries/-143724?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/athletes/5120814/injuries/-143065?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/events_basketball_nba_single_date_20250301.json
{
  "count": 6,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705426?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705427?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705428?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705429?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705430?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/events/401705431?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/coaches_baseball_mlb_2024_test.json
{
  "count": 30,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 2,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/341?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/160?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/55?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/257?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/192?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/86?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/181?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/152?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/170?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/165?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/177?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/247?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/25?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/184?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/157?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/150?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/2?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/194?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/154?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/163?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/193?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/183?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/339?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/178?lang=en&region=us"
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2024/coaches/167?lang=en&region=us"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/mlb_providers_list.json
{"count":55,"pageIndex":1,"pageSize":100,"pageCount":1,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/2?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/3?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/4?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/5?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/8?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/9?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/10?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/11?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/12?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/13?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/14?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/15?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/16?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/17?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/18?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/19?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/20?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/21?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/22?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/23?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/24?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/25?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/26?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/27?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/28?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/38?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/44?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/45?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/46?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/47?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/48?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/49?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/50?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/51?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/52?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/53?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/54?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/55?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/56?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/58?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/59?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1001?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1002?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1003?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1004?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1005?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1006?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1007?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1008?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1009?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/1010?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/2382?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/4000?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/providers/7874?lang=en&region=us"}]}

=== aaronweldy/espn-openapi/json_output/nfl_positions.json
{"count":74,"pageIndex":1,"pageSize":10,"pageCount":8,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/0?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/1?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/2?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/3?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/4?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/5?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/6?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/7?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/8?lang=en&region=us"},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/9?lang=en&region=us"}]}
