=== aaronweldy/espn-openapi/json_schemas/athlete_splits_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/AthleteSplitsSchema",
    "definitions": {
        "AthleteSplitsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Filter"
                    }
                },
                "displayName": {
                    "type": "string"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Category"
                    }
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "displayNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "descriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "splitCategories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SplitCategory"
                    }
                }
            },
            "required": [
                "categories",
                "descriptions",
                "displayName",
                "displayNames",
                "filters",
                "labels",
                "names",
                "splitCategories"
            ],
            "title": "AthleteSplitsSchema"
        },
        "Category": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            },
            "required": [
                "count",
                "displayName",
                "name"
            ],
            "title": "Category"
        },
        "Filter": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Option"
                    }
                }
            },
            "required": [
                "displayName",
                "name",
                "options",
                "value"
            ],
            "title": "Filter"
        },
        "Option": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string"
                },
                "displayValue": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                }
            },
            "required": [
                "displayValue",
                "value"
            ],
            "title": "Option"
        },
        "SplitCategory": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "splits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Split"
                    }
                }
            },
            "required": [
                "displayName",
                "name"
            ],
            "title": "SplitCategory"
        },
        "Split": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "abbreviation": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "stats"
            ],
            "title": "Split"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/athlete_2330_splits_processed.json
{
  "filters": [
    {
      "displayName": "League",
      "name": "league",
      "value": "nfl",
      "options": [
        {
          "value": "nfl",
          "displayValue": "National Football League",
          "shortDisplayName": "NFL"
        }
      ]
    },
    {
      "displayName": "Season",
      "name": "season",
      "value": "2022",
      "options": [
        {
          "value": "2022",
          "displayValue": "2022"
        },
        {
          "value": "2021",
          "displayValue": "2021"
        },
        {
          "value": "2020",
          "displayValue": "2020"
        },
        {
          "value": "2019",
          "displayValue": "2019"
        },
        {
          "value": "2018",
          "displayValue": "2018"
        },
        {
          "value": "2017",
          "displayValue": "2017"
        },
        {
          "value": "2016",
          "displayValue": "2016"
        },
        {
          "value": "2015",
          "displayValue": "2015"
        },
        {
          "value": "2014",
          "displayValue": "2014"
        },
        {
          "value": "2013",
          "displayValue": "2013"
        },
        {
          "value": "2012",
          "displayValue": "2012"
        },
        {
          "value": "2011",
          "displayValue": "2011"
        },
        {
          "value": "2010",
          "displayValue": "2010"
        },
        {
          "value": "2009",
          "displayValue": "2009"
        },
        {
          "value": "2008",
          "displayValue": "2008"
        },
        {
          "value": "2007",
          "displayValue": "2007"
        },
        {
          "value": "2006",
          "displayValue": "2006"
        },
        {
          "value": "2005",
          "displayValue": "2005"
        },
        {
          "value": "2004",
          "displayValue": "2004"
        },
        {
          "value": "2003",
          "displayValue": "2003"
        },
        {
          "value": "2002",
          "displayValue": "2002"
        },
        {
          "value": "2001",
          "displayValue": "2001"
        },
        {
          "value": "2000",
          "displayValue": "2000"
        }
      ]
    }
  ],
  "displayName": "2022 Splits",
  "categories": [
    {
      "name": "passing",
      "displayName": "Passing",
      "count": 9
    }
  ],
  "labels": [
    "CMP",
    "ATT",
    "YDS",
    "CMP%",
    "AVG",
    "TD",
    "INT",
    "LNG",
    "SACK",
    "RTG",
    "CAR",
    "YDS",
    "AVG",
    "TD",
    "LNG"
  ],
  "names": [
    "completions",
    "passingAttempts",
    "passingYards",
    "completionPct",
    "yardsPerPassAttempt",
    "passingTouchdowns",
    "interceptions",
    "longPassing",
    "sacks",
    "QBRating",
    "rushingAttempts",
    "rushingYards",
    "yardsPerRushAttempt",
    "rushingTouchdowns",
    "longRushing"
  ],
  "displayNames": [
    "Completions",
    "Passing Attempts",
    "Passing Yards",
    "Completion Percentage",
    "Yards Per Pass Attempt",
    "Passing Touchdowns",
    "Interceptions",
    "Longest Pass",
    "Total Sacks",
    "Passer Rating",
    "Rushing Attempts",
    "Rushing Yards",
    "Yards Per Rush Attempt",
    "Rushing Touchdowns",
    "Long Rushing"
  ],
  "descriptions": [
    "The times a player completes a pass to another player who is eligible to catch a pass.",
    "The number of times a pass is attempted.",
    "The total passing yards.",
    "The percentage of completed passes.",
    "The average number yards per pass attempt.",
    "The total number of passing touchdowns.",
    "The number of passes thrown that were intercepted by the opposing team.",
    "The longest pass play completed in terms of yards.",
    "The total number of sacks.",
    "Passer Rating",
    "The total number of attempted rushes.",
    "The total rushing yards.",
    "The average number of yards per rush attempt.",
    "The total number of rushing touchdowns.",
    "The amount of yards for the longest run."
  ],
  "splitCategories": [
    {
      "name": "split",
      "displayName": "split",
      "splits": [
        {
          "displayName": "All Splits",
          "stats": [
            "490",
            "733",
            "4,694",
            "66.8",
            "6.4",
            "25",
            "9",
            "63",
            "22",
            "90.7",
            "29",
            "-1",
            "0.0",
            "1",
            "2"
          ],
          "abbreviation": "Any"
        },
        {
          "displayName": "Home",
          "stats": [
            "289",
            "420",
            "2,895",
            "68.8",
            "6.9",
            "17",
            "4",
            "63",
            "13",
            "97.7",
            "17",
            "-2",
            "-0.1",
            "1",
            "2"
          ],
          "abbreviation": "Home"
        },
        {
          "displayName": "Away",
          "stats": [
            "201",
            "313",
            "1,799",
            "64.2",
            "5.7",
            "8",
            "5",
            "48",
            "9",
            "81.4",
            "12",
            "1",
            "0.1",
            "0",
            "2"
          ],
          "abbreviation": "Away"
        }
      ]
    },
    {
      "name": "byOutcome",
      "displayName": "Outcome",
      "splits": [
        {
          "displayName": "Wins/Ties",
          "stats": [
            "231",
            "347",
            "2,285",
            "66.6",
            "6.6",
            "12",
            "5",
            "63",
            "8",
            "90.5",
            "20",
            "-5",
            "-0.3",
            "1",
            "2"
          ],
          "abbreviation": "In Win"
        },
        {
          "displayName": "Losses",
          "stats": [
            "259",
            "386",
            "2,409",
            "67.1",
            "6.2",
            "13",
            "4",
            "51",
            "14",
            "90.9",
            "9",
            "4",
            "0.4",
            "0",
            "2"
          ],
          "abbreviation": "In Loss"
        }
      ]
    },
    {
      "name": "byVictoryMargin",
      "displayName": "Victory Margin",
      "splits": [
        {
          "displayName": "0-7",
          "stats": [
            "195",
            "286",
            "1,883",
            "68.2",
            "6.6",
            "10",
            "4",
            "63",
            "5",
            "92.2",
            "15",
            "-2",
            "-0.1",
            "1",
            "2"
          ],
          "abbreviation": "Mgn<8"
        },
        {
          "displayName": "8-14",
          "stats": [
            "18",
            "34",
            "190",
            "52.9",
            "5.6",
            "1",
            "0",
            "41",
            "1",
            "79.3",
            "3",
            "-2",
            "-0.7",
            "0",
            "0"
          ],
          "abbreviation": "Mgn 8-14"
        },
        {
          "displayName": "15+",
          "stats": [
            "18",
            "27",
            "212",
            "66.7",
            "7.9",
            "1",
            "1",
            "48",
            "2",
            "87.3",
            "2",
            "-1",
            "-0.5",
            "0",
            "0"
          ],
          "abbreviation": "Mgn>14"
        }
      ]
    },
    {
      "name": "byClose",
      "displayName": "Close",
      "splits": [
        {
          "displayName": "4th QTR, +/-7",
          "stats": [
            "55",
            "88",
            "539",
            "62.5",
            "6.1",
            "4",
            "0",
            "51",
            "3",
            "94.8",
            "9",
            "-1",
            "-0.1",
            "1",
            "2"
          ],
          "abbreviation": "Late&Close"
        },
        {
          "displayName": "Last 2 Min. Half",
          "stats": [
            "75",
            "116",
            "767",
            "64.7",
            "6.6",
            "7",
            "1",
            "48",
            "4",
            "100.0",
            "19",
            "-10",
            "-0.5",
            "1",
            "2"
          ],
          "abbreviation": "2 Min"
        }
      ]
    },
    {
      "name": "bySeasonGames",
      "displayName": "Season Games",
      "splits": [
        {
          "displayName": "1-8",
          "stats": [
            "224",
            "340",
            "2,267",
            "65.9",
            "6.7",
            "9",
            "1",
            "51",
            "13",
            "92.4",
            "12",
            "-5",
            "-0.4",
            "0",
            "1"
          ],
          "abbreviation": "Games 1-8"
        },
        {
          "displayName": "9-16",
          "stats": [
            "266",
            "393",
            "2,427",
            "67.7",
            "6.2",
            "16",
            "8",
            "63",
            "9",
            "89.3",
            "17",
            "4",
            "0.2",
            "1",
            "2"
          ],
          "abbreviation": "Games 9-16"
        }
      ]
    },
    {
      "name": "byMonth",
      "displayName": "Month",
      "splits": [
        {
          "displayName": "September",
          "stats": [
            "67",
            "103",
            "673",
            "65.0",
            "6.5",
            "3",
            "1",
            "48",
            "6",
            "89.2",
            "6",
            "-4",
            "-0.7",
            "0",
            "0"
          ],
          "abbreviation": "Sept"
        },
        {
          "displayName": "October",
          "stats": [
            "157",
            "237",
            "1,594",
            "66.2",
