=== aaronweldy/espn-openapi/json_schemas/core_nfl_transactions_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CoreNflTransactionsSchema",
    "definitions": {
        "CoreNflTransactionsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {}
                }
            },
            "required": [
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "CoreNflTransactionsSchema"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/odds_movement_football_nfl_401249063.json
{
  "count": 71,
  "pageIndex": 1,
  "pageSize": 100,
  "pageCount": 1,
  "items": [
    {
      "overOdds": 0.0,
      "underOdds": 0.0,
      "drawOdds": 0.0,
      "awayOdds": -110.0,
      "homeOdds": -106.0,
      "lineDate": "2020-10-18T11:13Z",
      "moneylineWinner": false,
      "spreadWinner": false,
      "line": 0.0
    },
    {
      "overOdds": 0.0,
      "underOdds": 0.0,
      "drawOdds": 0.0,
      "awayOdds": -112.0,
      "homeOdds": -104.0,
      "lineDate": "2020-10-19T06:12Z",
      "moneylineWinner": false,
      "spreadWinner": false,
      "line": 0.0
    },
    {
      "overOdds": 0.0,
      "underOdds": 0.0,
      "drawOdds": 0.0,
      "awayOdds": -126.0,
      "homeOdds": 108.0,
      "lineDate": "2020-10-19T06:52Z",
      "moneylineWinner": false,
      "spreadWinner": false,
      "line": 0.0
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/mlb_odds_401695789.json
{"count":1,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"provider":{"id":"58","name":"ESPN BET","priority":1},"details":"TEX -160","overUnder":7.5,"spread":-1.5,"initialSpread":0.0,"initialOverUnder":0.0,"price":0.0,"overOdds":-105.0,"underOdds":-115.0,"awayTeamOdds":{"favorite":false,"underdog":true,"moneyLine":135,"open":{"favorite":false,"pointSpread":{"alternateDisplayValue":"+3.5","american":"+3.5"},"spread":{"value":1.256,"displayValue":"10/39","alternateDisplayValue":"-390","decimal":1.256,"fraction":"10/39","american":"-390"},"moneyLine":{"value":2.5,"displayValue":"3/2","alternateDisplayValue":"+150","decimal":2.5,"fraction":"3/2","american":"+150"}},"close":{"pointSpread":{"alternateDisplayValue":"+1.5","american":"+1.5"},"spread":{"value":1.625,"displayValue":"5/8","alternateDisplayValue":"-160","decimal":1.625,"fraction":"5/8","american":"-160"},"moneyLine":{"value":2.35,"displayValue":"27/20","alternateDisplayValue":"+135","decimal":2.35,"fraction":"27/20","american":"+135"}},"current":{"pointSpread":{"alternateDisplayValue":"+1.5","american":"+1.5"},"spread":{"value":1.625,"displayValue":"5/8","alternateDisplayValue":"-160","decimal":1.625,"fraction":"5/8","american":"-160","outcome":{"type":"loss"}},"moneyLine":{"value":2.35,"displayValue":"27/20","alternateDisplayValue":"+135","decimal":2.35,"fraction":"27/20","american":"+135","outcome":{"type":"loss"}}},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/teams/24?lang=en&region=us"}},"homeTeamOdds":{"favorite":true,"underdog":false,"moneyLine":-160,"open":{"favorite":true,"pointSpread":{"value":3.6,"displayValue":"13/5","alternateDisplayValue":"-3.5","decimal":3.6,"fraction":"13/5","american":"-3.5"},"spread":{"value":3.6,"displayValue":"13/5","alternateDisplayValue":"+260","decimal":3.6,"fraction":"13/5","american":"+260"},"moneyLine":{"value":1.556,"displayValue":"5/9","alternateDisplayValue":"-180","decimal":1.556,"fraction":"5/9","american":"-180"}},"close":{"pointSpread":{"value":0.0,"alternateDisplayValue":"-1.5","decimal":0.0,"american":"-1.5"},"spread":{"value":2.35,"displayValue":"27/20","alternateDisplayValue":"+135","decimal":2.35,"fraction":"27/20","american":"+135"},"moneyLine":{"value":1.625,"displayValue":"5/8","alternateDisplayValue":"-160","decimal":1.625,"fraction":"5/8","american":"-160"}},"current":{"pointSpread":{"value":0.0,"alternateDisplayValue":"-1.5","decimal":0.0,"american":"-1.5"},"spread":{"value":2.35,"displayValue":"27/20","alternateDisplayValue":"+135","decimal":2.35,"fraction":"27/20","american":"+135","outcome":{"type":"win"}},"moneyLine":{"value":1.625,"displayValue":"5/8","alternateDisplayValue":"-160","decimal":1.625,"fraction":"5/8","american":"-160","outcome":{"type":"win"}}},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/teams/13?lang=en&region=us"}},"links":[{"language":"en-US","rel":["home","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=5f4596a6-95a4-4493-b42c-639839ebcbbb&odds_numerator[0]=13&odds_denominator[0]=8","text":"Home Bet","shortText":"Home Bet","isExternal":true,"isPremium":false},{"language":"en-US","rel":["away","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=fb2c0989-4fd8-4b0b-9c98-55f2b7788986&odds_numerator[0]=47&odds_denominator[0]=20","text":"Away Bet","shortText":"Away Bet","isExternal":true,"isPremium":false},{"language":"en-US","rel":["homeSpread","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=a0c63a92-62d4-4f18-9439-ff619ebe3542&odds_numerator[0]=47&odds_denominator[0]=20","text":"Home Point Spread","shortText":"Home Point Spread","isExternal":true,"isPremium":false},{"language":"en-US","rel":["awaySpread","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=e844b7c2-4718-47a9-9e19-a1527b58b7d4&odds_numerator[0]=13&odds_denominator[0]=8","text":"Away Point Spread","shortText":"Away Point Spread","isExternal":true,"isPremium":false},{"language":"en-US","rel":["over","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=091e10b9-0588-443e-acac-83b33f498ff6&odds_numerator[0]=41&odds_denominator[0]=21","text":"Over Odds","shortText":"Over Odds","isExternal":true,"isPremium":false},{"language":"en-US","rel":["under","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf&market_selection_id[0]=e74ddeb2-167c-43b6-aa72-28143936ff5c&odds_numerator[0]=43&odds_denominator[0]=23","text":"Under Odds","shortText":"Under Odds","isExternal":true,"isPremium":false},{"language":"en-US","rel":["game","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/15798e35-2be2-45e2-967d-6a6367119fdf","text":"Game","shortText":"Game","isExternal":true,"isPremium":false}],"moneylineWinner":false,"spreadWinner":false,"open":{"over":{"value":1.952,"displayValue":"20/21","alternateDisplayValue":"-105","decimal":1.952,"fraction":"20/21","american":"-105"},"under":{"value":1.87,"displayValue":"20/23","alternateDisplayValue":"-115","decimal":1.87,"fraction":"20/23","american":"-115"},"total":{"value":1.952,"displayValue":"20/21","alternateDisplayValue":"7.5","decimal":1.952,"fraction":"20/21","american":"7.5"}},"close":{"over":{"value":1.952,"displayValue":"20/21","alternateDisplayValue":"-105","decimal":1.952,"fraction":"20/21","american":"-105"},"under":{"value":1.87,"displayValue":"20/23","alternateDisplayValue":"-115","decimal":1.87,"fraction":"20/23","american":"-115"},"total":{"value":0.0,"alternateDisplayValue":"7.5","decimal":0.0,"american":"7.5"}},"current":{"over":{"value":1.952,"displayValue":"20/21","alternateDisplayValue":"-105","decimal":1.952,"fraction":"20/21","american":"-105","outcome":{"type":"win"}},"under":{"value":1.87,"displayValue":"20/23","alternateDisplayValue":"-115","decimal":1.87,"fraction":"20/23","american":"-115","outcome":{"type":"loss"}},"total":{"value":0.0,"alternateDisplayValue":"7.5","decimal":0.0,"american":"7.5"}},"propBets":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/events/401695789/competitions/401695789/odds/58/propBets?lang=en&region=us"}}]}

=== aaronweldy/espn-openapi/json_output/odds_predictors_nfl_401326317_provider1003_multi_events_test.json
{
  "count": 5,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "rank": 1,
      "value": 91.999,
      "displayValue": "92.0",
      "total": "OVER",
      "predictorCompetition": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326317/competitions/401326317?lang=en&region=us"
      },
      "projectedWinner": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/2?lang=en&region=us"
      },
      "cover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/2?lang=en&region=us"
      },
      "projectedCover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/25?lang=en&region=us"
      }
    },
    {
      "rank": 2,
      "value": 91.629,
      "displayValue": "91.6",
      "total": "OVER",
      "predictorCompetition": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326317/competitions/401326317?lang=en&region=us"
      },
      "projectedWinner": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/1?lang=en&region=us"
      },
      "cover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/1?lang=en&region=us"
      },
      "projectedCover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/8?lang=en&region=us"
      }
    },
    {
      "rank": 3,
      "value": 91.164,
      "displayValue": "91.2",
      "total": "OVER",
      "predictorCompetition": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326317/competitions/401326317?lang=en&region=us"
      },
      "projectedWinner": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/19?lang=en&region=us"
      },
      "cover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/19?lang=en&region=us"
      },
      "projectedCover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/25?lang=en&region=us"
      }
    },
    {
      "rank": 4,
      "value": 91.07,
      "displayValue": "91.1",
      "total": "UNDER",
      "predictorCompetition": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326317/competitions/401326317?lang=en&region=us"
      },
      "projectedWinner": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/22?lang=en&region=us"
      },
      "cover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/22?lang=en&region=us"
      },
      "projectedCover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/8?lang=en&region=us"
      }
    },
    {
      "rank": 5,
      "value": 90.957,
      "displayValue": "91.0",
      "total": "UNDER",
      "predictorCompetition": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326317/competitions/401326317?lang=en&region=us"
      },
      "projectedWinner": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/22?lang=en&region=us"
      },
      "cover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/22?lang=en&region=us"
      },
      "projectedCover": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/25?lang=en&region=us"
      }
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/nfl_team_odds_records_test.json
{"count":10,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"abbreviation":"ML","displayName":"Money Line Overall Record","shortDisplayName":"Money Line","type":"moneyLineOverall","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":16.0,"displayValue":"16"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":3.0,"displayValue":"3"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":7.21,"displayValue":"7.210"}]},{"abbreviation":"ML HOME","displayName":"Money Line Home Record","shortDisplayName":"Money Line Home","type":"moneyLineHome","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":9.0,"displayValue":"9"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":1.0,"displayValue":"1"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":5.6,"displayValue":"5.600"}]},{"abbreviation":"ML AWAY","displayName":"Money Line Away Record","shortDisplayName":"Money Line Away","type":"moneyLineAway","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":7.0,"displayValue":"7"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":2.0,"displayValue":"2"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":9.0,"displayValue":"9.000"}]},{"abbreviation":"ML UND","displayName":"Money Line Record as Underdog","shortDisplayName":"Money Line Underdog","type":"moneyLineUnderdog","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":1.0,"displayValue":"1"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":1.0,"displayValue":"1"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":3.0,"displayValue":"3.000"}]},{"abbreviation":"ML FAV","displayName":"Money Line Record as Favorite","shortDisplayName":"Money Line Favorite","type":"moneyLineFavorite","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":15.0,"displayValue":"15"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":2.0,"displayValue":"2"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":7.71,"displayValue":"7.710"}]},{"abbreviation":"ATS","displayName":"Spread Overall Record","shortDisplayName":"Spread Overall","type":"spreadOverall","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":7.0,"displayValue":"7"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":11.0,"displayValue":"11"},{"displayName":"Ties","abbreviation":"T","type":"push","value":1.0,"displayValue":"1"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":0.37,"displayValue":"0.370"}]},{"abbreviation":"ATS HOME","displayName":"Spread Home Record","shortDisplayName":"Spread Home","type":"spreadHome","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":3.0,"displayValue":"3"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":6.0,"displayValue":"6"},{"displayName":"Ties","abbreviation":"T","type":"push","value":1.0,"displayValue":"1"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":-2.6,"displayValue":"-2.600"}]},{"abbreviation":"ATS AWAY","displayName":"Spread Away Record","shortDisplayName":"Spread Away","type":"spreadAway","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":4.0,"displayValue":"4"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":5.0,"displayValue":"5"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":3.67,"displayValue":"3.670"}]},{"abbreviation":"ATS UND","displayName":"Spread Record as Underdog","shortDisplayName":"Spread Underdog","type":"spreadUnderdog","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":1.0,"displayValue":"1"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":1.0,"displayValue":"1"},{"displayName":"Ties","abbreviation":"T","type":"push","value":0.0,"displayValue":"0"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":5.25,"displayValue":"5.250"}]},{"abbreviation":"ATS FAV","displayName":"Spread Record as Favorite","shortDisplayName":"Spread Favorite","type":"spreadFavorite","stats":[{"displayName":"Wins","abbreviation":"W","type":"win","value":6.0,"displayValue":"6"},{"displayName":"Losses","abbreviation":"L","type":"loss","value":10.0,"displayValue":"10"},{"displayName":"Ties","abbreviation":"T","type":"push","value":1.0,"displayValue":"1"},{"displayName":"Over Total","abbreviation":"Over","type":"overTotal","value":0.0,"displayValue":"0"},{"displayName":"Under Total","abbreviation":"Under","type":"underTotal","value":0.0,"displayValue":"0"},{"displayName":"Margin","abbreviation":"Margin","type":"margin","value":-0.21,"displayValue":"-0.210"}]}]}

=== aaronweldy/espn-openapi/json_output/nfl_conference_standings_2023_nfc.json
{"count":4,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/types/2/groups/7/standings/0?lang=en&region=us","id":"0","name":"overall","displayName":"Standings","links":[{"language":"en-US","rel":["standings","desktop"],"href":"https://www.espn.com/nfl/standings/_/group/7","text":"Table","shortText":"Standings","isExternal":false,"isPremium":false}]},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/types/2/groups/7/standings/1?lang=en&region=us","id":"1","name":"playoff","displayName":"Playoff Standings","links":[{"language":"en-US","rel":["standings","desktop"],"href":"https://www.espn.com/nfl/standings/_/group/7","text":"Table","shortText":"Standings","isExternal":false,"isPremium":false}]},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/types/2/groups/7/standings/2?lang=en&region=us","id":"2","name":"expanded","displayName":"Expanded Standings","links":[{"language":"en-US","rel":["standings","desktop"],"href":"https://www.espn.com/nfl/standings/_/group/7","text":"Table","shortText":"Standings","isExternal":false,"isPremium":false}]},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/types/2/groups/7/standings/3?lang=en&region=us","id":"3","name":"division","displayName":"Vs. Division Standings","links":[{"language":"en-US","rel":["standings","desktop"],"href":"https://www.espn.com/nfl/standings/_/group/7","text":"Table","shortText":"Standings","isExternal":false,"isPremium":false}]}]}

=== aaronweldy/espn-openapi/json_output/athlete_notes_mlb_33912_2024.json
{
  "count": 1,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "id": "966161",
      "type": "news",
      "date": "2025-06-01T21:12Z",
      "headline": "Bellinger is out of the lineup for Sunday's game against the Dodgers.",
      "text": "Bellinger had started in each of the Yankees' last seven games, but he went just 6-for-27 (.222 average) during that stretch and now finds himself on the bench Sunday. With Bellinger sitting, the Yankees will roll out a starting outfield of Jasson Dominguez, Trent Grisham and Aaron Judge from left to right.",
      "source": "RotoWire"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/tigers_whitesox_odds_june5.json
{"count":1,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"provider":{"id":"58","name":"ESPN BET","priority":1},"details":"DET -215","overUnder":8.5,"spread":1.5,"initialSpread":0.0,"initialOverUnder":0.0,"price":0.0,"overOdds":-105.0,"underOdds":-115.0,"awayTeamOdds":{"favorite":true,"underdog":false,"moneyLine":-215,"open":{"favorite":true,"pointSpread":{"alternateDisplayValue":"-2.5","american":"-2.5"},"spread":{"value":2.25,"displayValue":"5/4","alternateDisplayValue":"+125","decimal":2.25,"fraction":"5/4","american":"+125"},"moneyLine":{"value":1.465,"displayValue":"20/43","alternateDisplayValue":"-215","decimal":1.465,"fraction":"20/43","american":"-215"}},"close":{"pointSpread":{"alternateDisplayValue":"EVEN","american":"EVEN"}},"current":{"pointSpread":{"alternateDisplayValue":"-1.5","american":"-1.5"},"spread":{"value":1.769,"displayValue":"10/13","alternateDisplayValue":"-130","decimal":1.769,"fraction":"10/13","american":"-130","outcome":{"type":"pending"}},"moneyLine":{"value":1.465,"displayValue":"20/43","alternateDisplayValue":"-215","decimal":1.465,"fraction":"20/43","american":"-215","outcome":{"type":"pending"}}},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/teams/6?lang=en&region=us"}},"homeTeamOdds":{"favorite":false,"underdog":true,"moneyLine":180,"open":{"favorite":false,"pointSpread":{"value":1.667,"displayValue":"2/3","alternateDisplayValue":"+2.5","decimal":1.667,"fraction":"2/3","american":"+2.5"},"spread":{"value":1.667,"displayValue":"2/3","alternateDisplayValue":"-150","decimal":1.667,"fraction":"2/3","american":"-150"},"moneyLine":{"value":2.8,"displayValue":"9/5","alternateDisplayValue":"+180","decimal":2.8,"fraction":"9/5","american":"+180"}},"close":{"pointSpread":{"value":0.0,"alternateDisplayValue":"EVEN","decimal":0.0,"american":"EVEN"}},"current":{"pointSpread":{"value":0.0,"alternateDisplayValue":"+1.5","decimal":0.0,"american":"+1.5"},"spread":{"value":2.1,"displayValue":"11/10","alternateDisplayValue":"+110","decimal":2.1,"fraction":"11/10","american":"+110","outcome":{"type":"pending"}},"moneyLine":{"value":2.8,"displayValue":"9/5","alternateDisplayValue":"+180","decimal":2.8,"fraction":"9/5","american":"+180","outcome":{"type":"pending"}}},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/seasons/2025/teams/4?lang=en&region=us"}},"links":[{"language":"en-US","rel":["home","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=153f2f45-0ac8-41dc-a39d-947f6bff992a&odds_numerator[0]=14&odds_denominator[0]=5","text":"Home Bet","shortText":"Home Bet","isExternal":true,"isPremium":false},{"language":"en-US","rel":["away","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=54570294-cefa-4bc9-ad07-87b4089cd2f5&odds_numerator[0]=63&odds_denominator[0]=43","text":"Away Bet","shortText":"Away Bet","isExternal":true,"isPremium":false},{"language":"en-US","rel":["homeSpread","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=5ed1e194-39a0-4ece-906c-4ddc42b750a6&odds_numerator[0]=21&odds_denominator[0]=10","text":"Home Point Spread","shortText":"Home Point Spread","isExternal":true,"isPremium":false},{"language":"en-US","rel":["awaySpread","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=fa6ab754-2b1a-4eee-9500-82d5d2d4761d&odds_numerator[0]=23&odds_denominator[0]=13","text":"Away Point Spread","shortText":"Away Point Spread","isExternal":true,"isPremium":false},{"language":"en-US","rel":["over","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=2e937a05-23e8-4fc9-bca8-b14fe61e389d&odds_numerator[0]=41&odds_denominator[0]=21","text":"Over Odds","shortText":"Over Odds","isExternal":true,"isPremium":false},{"language":"en-US","rel":["under","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1&market_selection_id[0]=4cd35b56-81e1-440e-a694-d4dc6243021a&odds_numerator[0]=43&odds_denominator[0]=23","text":"Under Odds","shortText":"Under Odds","isExternal":true,"isPremium":false},{"language":"en-US","rel":["game","desktop","bets"],"href":"https://espnbet.app.link/integrations?%243p=a_espn&clr=espnbettingintegration&$canonical_url=/sport/baseball/organization/united-states/competition/mlb/event/a15fbe1a-6c11-4b5c-8a6c-19ef99d6fab1","text":"Game","shortText":"Game","isExternal":true,"isPremium":false}],"moneylineWinner":false,"spreadWinner":false,"open":{"under":{"value":2.2,"displayValue":"6/5","alternateDisplayValue":"+120","decimal":2.2,"fraction":"6/5","american":"+120"},"total":{"value":0.0,"alternateDisplayValue":"6.5","decimal":0.0,"american":"6.5"}},"current":{"over":{"value":1.952,"displayValue":"20/21","alternateDisplayValue":"-105","decimal":1.952,"fraction":"20/21","american":"-105","outcome":{"type":"pending"}},"under":{"value":1.87,"displayValue":"20/23","alternateDisplayValue":"-115","decimal":1.87,"fraction":"20/23","american":"-115","outcome":{"type":"pending"}},"total":{"value":0.0,"alternateDisplayValue":"8.5","decimal":0.0,"american":"8.5"}},"propBets":{"$ref":"http://sports.core.api.espn.com/v2/sports/baseball/leagues/mlb/events/401695838/competitions/401695838/odds/58/propBets?lang=en&region=us"}}]}
