=== aaronweldy/espn-openapi/json_schemas/core_nfl_transactions_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CoreNflTransactionsSchema",
    "definitions": {
        "CoreNflTransactionsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {}
                }
            },
            "required": [
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "CoreNflTransactionsSchema"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/linescores_football_nfl_401437954_competitor30.json
{
  "count": 4,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401437954/competitions/401437954/competitors/30/linescores/1/1?lang=en&region=us",
      "value": 0.0,
      "displayValue": "0",
      "source": {
        "id": "1",
        "description": "Basic/Manual"
      },
      "period": 1
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401437954/competitions/401437954/competitors/30/linescores/1/2?lang=en&region=us",
      "value": 7.0,
      "displayValue": "7",
      "source": {
        "id": "1",
        "description": "Basic/Manual"
      },
      "period": 2
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401437954/competitions/401437954/competitors/30/linescores/1/3?lang=en&region=us",
      "value": 3.0,
      "displayValue": "3",
      "source": {
        "id": "1",
        "description": "Basic/Manual"
      },
      "period": 3
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401437954/competitions/401437954/competitors/30/linescores/1/4?lang=en&region=us",
      "value": 10.0,
      "displayValue": "10",
      "source": {
        "id": "1",
        "description": "Basic/Manual"
      },
      "period": 4
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/team_records_nfl_401547417_competitor9.json
{"count":3,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/records/369?lang=en&region=us","id":"369","name":"overall","abbreviation":"Game","displayName":"Record Year To Date","shortDisplayName":"YTD","description":"Overall Record","type":"total","summary":"1-1","displayValue":"1-1","value":0.5,"stats":[{"name":"OTLosses","displayName":"Overtime Losses","shortDisplayName":"OTL","description":"Number of Overtime Losses","abbreviation":"OTL","type":"otlosses","value":0.0,"displayValue":"0"},{"name":"OTWins","displayName":"Overtime Wins","shortDisplayName":"OT Wins","description":"Number of Overtime Wins","abbreviation":"OTW","type":"otwins","value":0.0,"displayValue":"0"},{"name":"avgPointsAgainst","displayName":"Opponent Points Per Game","shortDisplayName":"OPTS/G","description":"Opponent Points Per Game","abbreviation":"OPTS/G","type":"avgpointsagainst","value":12.5,"displayValue":"12.5"},{"name":"avgPointsFor","displayName":"Points Per Game","shortDisplayName":"PTS/G","description":"Points Per Game","abbreviation":"PTS/G","type":"avgpointsfor","value":12.0,"displayValue":"12.0"},{"name":"differential","displayName":"Point Differential","shortDisplayName":"DIFF","description":"Point Differential","abbreviation":"DIFF","type":"differential","value":-1.0,"displayValue":"-1"},{"name":"divisionWinPercent","displayName":"Division Win Percentage","shortDisplayName":"DPCT","description":"Division Winning Percentage","abbreviation":"DPCT","type":"divisionwinpercent","value":1.0,"displayValue":"1.000"},{"name":"gamesBehind","displayName":"Games Back","shortDisplayName":"GB","description":"Games Back","abbreviation":"GB","type":"gamesbehind","value":0.0,"displayValue":"-"},{"name":"gamesPlayed","displayName":"Games Played","shortDisplayName":"GP","description":"Games Played","abbreviation":"GP","type":"gamesplayed","value":2.0,"displayValue":"2"},{"name":"leagueWinPercent","displayName":"League Win Percentage","shortDisplayName":"LPCT","description":"League Winning Percentage","abbreviation":"LPCT","type":"leaguewinpercent","value":0.5,"displayValue":"0.500"},{"name":"losses","displayName":"Losses","shortDisplayName":"L","description":"Losses","abbreviation":"L","type":"losses","value":1.0,"displayValue":"1"},{"name":"playoffSeed","displayName":"Position","shortDisplayName":"POS","description":"Playoff Seed","abbreviation":"SEED","type":"playoffseed","value":4.0,"displayValue":"4"},{"name":"pointDifferential","displayName":"Point Differential","shortDisplayName":"DIFF","description":"Point Differential","abbreviation":"DIFF","type":"pointdifferential","value":-1.0,"displayValue":"-1"},{"name":"points","displayName":"Points","shortDisplayName":"PTS","description":"Total Points","abbreviation":"PTS","type":"points","value":0.0,"displayValue":"0.0"},{"name":"pointsAgainst","displayName":"Points Against","shortDisplayName":"PA","description":"Total Points Against","abbreviation":"PA","type":"pointsagainst","value":25.0,"displayValue":"25"},{"name":"pointsFor","displayName":"Points For","shortDisplayName":"PF","description":"Total Points For","abbreviation":"PF","type":"pointsfor","value":24.0,"displayValue":"24"},{"name":"streak","displayName":"Streak","shortDisplayName":"STRK","description":"Current Streak","abbreviation":"STRK","type":"streak","value":-1.0,"displayValue":"L1"},{"name":"ties","displayName":"Ties","shortDisplayName":"T","description":"Ties","abbreviation":"T","type":"ties","value":0.0,"displayValue":"0"},{"name":"winPercent","displayName":"Win Percentage","shortDisplayName":"PCT","description":"Winning Percentage","abbreviation":"PCT","type":"winpercent","value":0.5,"displayValue":".500"},{"name":"wins","displayName":"Wins","shortDisplayName":"W","description":"Wins","abbreviation":"W","type":"wins","value":1.0,"displayValue":"1"},{"name":"divisionLosses","displayName":"Division Losses","shortDisplayName":"DL","description":"Division Losses","abbreviation":"DL","type":"divisionlosses","value":0.0,"displayValue":"0"},{"name":"divisionRecord","displayName":"Division record","shortDisplayName":"DIV","description":"Division Record","abbreviation":"DIV","type":"divisionrecord","value":0.0,"displayValue":"1-0"},{"name":"divisionTies","displayName":"Division Tie ","shortDisplayName":"DT","description":"Division Tie ","abbreviation":"DT","type":"divisionties","value":0.0,"displayValue":"0.000"},{"name":"divisionWins","displayName":"Division Wins ","shortDisplayName":"DW","description":"Division Winning ","abbreviation":"DW","type":"divisionwins","value":1.0,"displayValue":"1.000"}]},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/records/13?lang=en&region=us","id":"13","name":"Home","displayName":"Home","shortDisplayName":"HOME","description":"Home Record","type":"home","summary":"0-0","displayValue":"0-0","stats":[{"name":"wins","displayName":"Wins","shortDisplayName":"W","description":"Wins","abbreviation":"W","type":"wins","value":0.0,"displayValue":"0"},{"name":"losses","displayName":"Losses","shortDisplayName":"L","description":"Losses","abbreviation":"L","type":"losses","value":0.0,"displayValue":"0"},{"name":"ties","displayName":"Ties","shortDisplayName":"T","description":"Ties","abbreviation":"T","type":"ties","value":0.0,"displayValue":"0"},{"name":"winPercent","displayName":"Win Percentage","shortDisplayName":"PCT","description":"Winning Percentage","abbreviation":"PCT","type":"winpercent","value":0.0,"displayValue":".000"},{"name":"OTLosses","displayName":"Overtime Losses","shortDisplayName":"OTL","description":"Number of Overtime Losses","abbreviation":"OTL","type":"otlosses","value":0.0,"displayValue":"0"}]},{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/records/14?lang=en&region=us","id":"14","name":"Road","displayName":"Road","shortDisplayName":"AWAY","description":"Away Record","type":"road","summary":"1-1","displayValue":"1-1","value":0.5,"stats":[{"name":"wins","displayName":"Wins","shortDisplayName":"W","description":"Wins","abbreviation":"W","type":"wins","value":1.0,"displayValue":"1"},{"name":"losses","displayName":"Losses","shortDisplayName":"L","description":"Losses","abbreviation":"L","type":"losses","value":1.0,"displayValue":"1"},{"name":"ties","displayName":"Ties","shortDisplayName":"T","description":"Ties","abbreviation":"T","type":"ties","value":0.0,"displayValue":"0"},{"name":"winPercent","displayName":"Win Percentage","shortDisplayName":"PCT","description":"Winning Percentage","abbreviation":"PCT","type":"winpercent","value":0.5,"displayValue":".500"},{"name":"OTLosses","displayName":"Overtime Losses","shortDisplayName":"OTL","description":"Number of Overtime Losses","abbreviation":"OTL","type":"otlosses","value":0.0,"displayValue":"0"}]}]}

=== aaronweldy/espn-openapi/json_output/competitor_records_nfl_401437954_30.json
{
  "count": 3,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401437954/competitions/401437954/competitors/30/records/369?lang=en&region=us",
      "id": "369",
      "name": "overall",
      "abbreviation": "Game",
      "displayName": "Record Year To Date",
      "shortDisplayName": "YTD",
      "description": "Overall Record",
      "type": "total",
      "summary": "9-8",
      "displayValue": "9-8",
      "value": 0.5294117647058824,
      "stats": [
        {
          "name": "wins",
          "displayName": "Wins",
          "shortDisplayName": "W",
          "description": "Wins",
          "abbreviation": "W",
          "type": "wins",
          "value": 9.0,
          "displayValue": "9"
        }
      ]
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/nfl_team_ats_records_2023_type2_team12.json
{
  "count": 8,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "wins": 9,
      "losses": 7,
      "pushes": 1,
      "type": {
        "id": "0",
        "name": "atsOverall",
        "description": "Overall team season record against the spread"
      }
    },
    {
      "wins": 8,
      "losses": 7,
      "pushes": 1,
      "type": {
        "id": "1",
        "name": "atsFavorite",
        "description": "Team season record against the spread as the favorite"
      }
    },
    {
      "wins": 1,
      "losses": 0,
      "pushes": 0,
      "type": {
        "id": "2",
        "name": "atsUnderdog",
        "description": "Team season record against the spread as the underdog"
      }
    },
    {
      "wins": 4,
      "losses": 3,
      "pushes": 1,
      "type": {
        "id": "3",
        "name": "atsAway",
        "description": "Team season record against the spread as the away team"
      }
    },
    {
      "wins": 5,
      "losses": 4,
      "pushes": 0,
      "type": {
        "id": "4",
        "name": "atsHome",
        "description": "Team season record against the spread as the home team"
      }
    },
    {
      "wins": 3,
      "losses": 3,
      "pushes": 1,
      "type": {
        "id": "5",
        "name": "atsAwayFavorite",
        "description": "Team season record against the spread as the away favorite"
      }
    },
    {
      "wins": 1,
      "losses": 0,
      "pushes": 0,
      "type": {
        "id": "6",
        "name": "atsAwayUnderdog",
        "description": "Team season record against the spread as the away underdog"
      }
    },
    {
      "wins": 5,
      "losses": 4,
      "pushes": 0,
      "type": {
        "id": "7",
        "name": "atsHomeFavorite",
        "description": "Team season record against the spread as the home favorite"
      }
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/athlete_notes_nba_1966_2025.json
{
  "count": 1,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "id": "494641",
      "type": "news",
      "date": "2025-05-01T09:55Z",
      "headline": "James closed with 22 points (9-21 FG, 1-5 3Pt, 3-6 FT), seven rebounds, six assists and two steals across 40 minutes during Wednesday's 103-96 loss to the Timberwolves in Game 5 of the first round of the Western Conference playoffs.",
      "text": "The home crowd might have seen James' last appearance in a Laker uniform Tuesday evening, as the rumors about his retirement dominated the post-game conversation. James faced the same scrutiny last season after the Lakers fell to the Nuggets, but he left little doubt about his return once Bronny James was added to the Lakers' roster. With his dream of playing alongside his son satisfied, James may decide to hang it up, but it's an open question for the time being.",
      "source": "RotoWire"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/athlete_notes_football_3139477_2025_test.json
{
  "count": 1,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "id": "597206",
      "type": "news",
      "date": "2025-03-12T15:55:00+00:00",
      "headline": "Mahomes agreed Wednesday with the Chiefs on a restructure of his contract, Adam Teicher of ESPN.com reports.",
      "text": "Mahomes and star defensive tackle Chris Jones both agreed to restructure their contracts Wednesday, freeing up a total of $49.4 million in cap space to help Kansas City maneuver in free agency. The team has already committed to a handful of key moves, including re-signing wideout Hollywood Brown to a one-year deal, placing the franchise tag on right guard Trey Smith and retaining linebacker Nick Bolton via a three-year contract. Mahomes remains signed through the 2031 season, and he'll enter the 2025 season with a reloaded supporting cast as the Chiefs work to bounce back from a disappointing 40-22 loss to the Eagles in Super Bowl LIX.",
      "source": "RotoWire"
    }
  ]
}

=== aaronweldy/espn-openapi/json_output/soccer_standings_core_api.json
{"count":1,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"$ref":"http://sports.core.api.espn.com/v2/sports/soccer/leagues/eng.1/seasons/2024/types/1/standings/0?lang=en&region=us","id":"0","name":"overall","displayName":"Standings","links":[{"language":"en-US","rel":["standings","desktop"],"href":"https://www.espn.com/soccer/table/_/league/eng.1","text":"Full Table","shortText":"Standings","isExternal":false,"isPremium":false}]}]}

=== aaronweldy/espn-openapi/json_output/odds_predictors_nfl_401326315_provider1003.json
{"count":5,"pageIndex":1,"pageSize":25,"pageCount":1,"items":[{"rank":1,"total":"OVER","value":90.363,"displayValue":"90.4","predictorCompetition":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326315/competitions/401326315?lang=en&region=us"},"projectedWinner":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/8?lang=en&region=us"},"cover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/8?lang=en&region=us"},"projectedCover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/1?lang=en&region=us"}},{"rank":2,"total":"UNDER","value":90.246,"displayValue":"90.2","predictorCompetition":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326315/competitions/401326315?lang=en&region=us"},"projectedWinner":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/33?lang=en&region=us"},"cover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/33?lang=en&region=us"},"projectedCover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/1?lang=en&region=us"}},{"rank":3,"total":"OVER","value":89.454,"displayValue":"89.5","predictorCompetition":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326315/competitions/401326315?lang=en&region=us"},"projectedWinner":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/23?lang=en&region=us"},"cover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/23?lang=en&region=us"},"projectedCover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/1?lang=en&region=us"}},{"rank":4,"total":"UNDER","value":88.914,"displayValue":"88.9","predictorCompetition":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326315/competitions/401326315?lang=en&region=us"},"projectedWinner":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/6?lang=en&region=us"},"cover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/6?lang=en&region=us"},"projectedCover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/21?lang=en&region=us"}},{"rank":5,"total":"UNDER","value":88.869,"displayValue":"88.9","predictorCompetition":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401326315/competitions/401326315?lang=en&region=us"},"projectedWinner":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/22?lang=en&region=us"},"cover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/25?lang=en&region=us"},"projectedCover":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2021/teams/21?lang=en&region=us"}}]}
