=== aaronweldy/espn-openapi/json_schemas/core_nfl_competition_officials_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CoreNflCompetitionOfficialsSchema",
    "definitions": {
        "CoreNflCompetitionOfficialsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Item"
                    }
                }
            },
            "required": [
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "CoreNflCompetitionOfficialsSchema"
        },
        "Item": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/Position"
                },
                "order": {
                    "type": "integer"
                }
            },
            "required": [
                "$ref",
                "displayName",
                "firstName",
                "fullName",
                "id",
                "lastName",
                "order",
                "position"
            ],
            "title": "Item"
        },
        "Position": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "displayName",
                "id",
                "name"
            ],
            "title": "Position"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/competition_401547417_officials.json
{
  "count": 7,
  "pageIndex": 1,
  "pageSize": 25,
  "pageCount": 1,
  "items": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/17660?lang=en&region=us",
      "id": "17660",
      "firstName": "Tony",
      "lastName": "Michalek",
      "fullName": "Tony Michalek",
      "displayName": "Tony Michalek",
      "position": {
        "id": "116",
        "name": "Umpire",
        "displayName": "Umpire"
      },
      "order": 1
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/2615382?lang=en&region=us",
      "id": "2615382",
      "firstName": "Tom",
      "lastName": "Hill",
      "fullName": "Tom Hill",
      "displayName": "Tom Hill",
      "position": {
        "id": "111",
        "name": "Field Judge",
        "displayName": "Field Judge"
      },
      "order": 2
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/2616568?lang=en&region=us",
      "id": "2616568",
      "firstName": "Todd",
      "lastName": "Prukop",
      "fullName": "Todd Prukop",
      "displayName": "Todd Prukop",
      "position": {
        "id": "110",
        "name": "Back Judge",
        "displayName": "Back Judge"
      },
      "order": 3
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/3055007?lang=en&region=us",
      "id": "3055007",
      "firstName": "Pat",
      "lastName": "Turner",
      "fullName": "Pat Turner",
      "displayName": "Pat Turner",
      "position": {
        "id": "112",
        "name": "Head Linesman",
        "displayName": "Head Linesman"
      },
      "order": 4
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/4374126?lang=en&region=us",
      "id": "4374126",
      "firstName": "Don",
      "lastName": "Willard",
      "fullName": "Don Willard",
      "displayName": "Don Willard",
      "position": {
        "id": "115",
        "name": "Side Judge",
        "displayName": "Side Judge"
      },
      "order": 5
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/4693713?lang=en&region=us",
      "id": "4693713",
      "firstName": "Daniel",
      "lastName": "Gallagher",
      "fullName": "Daniel Gallagher",
      "displayName": "Daniel Gallagher",
      "position": {
        "id": "113",
        "name": "Line Judge",
        "displayName": "Line Judge"
      },
      "order": 6
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials/4693718?lang=en&region=us",
      "id": "4693718",
      "firstName": "Tra",
      "lastName": "Blake",
      "fullName": "Tra Blake",
      "displayName": "Tra Blake",
      "position": {
        "id": "114",
        "name": "Referee",
        "displayName": "Referee"
      },
      "order": 7
    }
  ]
}
