=== aaronweldy/espn-openapi/json_schemas/core_nfl_event_competition_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CoreNflEventCompetitionSchema",
    "definitions": {
        "CoreNflEventCompetitionSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "guid": {
                    "type": "string",
                    "format": "uuid"
                },
                "uid": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "attendance": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/Type"
                },
                "timeValid": {
                    "type": "boolean"
                },
                "dateValid": {
                    "type": "boolean"
                },
                "neutralSite": {
                    "type": "boolean"
                },
                "divisionCompetition": {
                    "type": "boolean"
                },
                "conferenceCompetition": {
                    "type": "boolean"
                },
                "previewAvailable": {
                    "type": "boolean"
                },
                "recapAvailable": {
                    "type": "boolean"
                },
                "boxscoreAvailable": {
                    "type": "boolean"
                },
                "lineupAvailable": {
                    "type": "boolean"
                },
                "gamecastAvailable": {
                    "type": "boolean"
                },
                "playByPlayAvailable": {
                    "type": "boolean"
                },
                "conversationAvailable": {
                    "type": "boolean"
                },
                "commentaryAvailable": {
                    "type": "boolean"
                },
                "pickcenterAvailable": {
                    "type": "boolean"
                },
                "summaryAvailable": {
                    "type": "boolean"
                },
                "liveAvailable": {
                    "type": "boolean"
                },
                "ticketsAvailable": {
                    "type": "boolean"
                },
                "shotChartAvailable": {
                    "type": "boolean"
                },
                "timeoutsAvailable": {
                    "type": "boolean"
                },
                "possessionArrowAvailable": {
                    "type": "boolean"
                },
                "onWatchESPN": {
                    "type": "boolean"
                },
                "recent": {
                    "type": "boolean"
                },
                "bracketAvailable": {
                    "type": "boolean"
                },
                "wallclockAvailable": {
                    "type": "boolean"
                },
                "highlightsAvailable": {
                    "type": "boolean"
                },
                "gameSource": {
                    "$ref": "#/definitions/Source"
                },
                "boxscoreSource": {
                    "$ref": "#/definitions/Source"
                },
                "playByPlaySource": {
                    "$ref": "#/definitions/Source"
                },
                "linescoreSource": {
                    "$ref": "#/definitions/Source"
                },
                "statsSource": {
                    "$ref": "#/definitions/Source"
                },
                "venue": {
                    "$ref": "#/definitions/Venue"
                },
                "competitors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Competitor"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {}
                },
                "situation": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "status": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "odds": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "broadcasts": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "officials": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "details": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "leaders": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "predictor": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "probabilities": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "powerIndexes": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "format": {
                    "$ref": "#/definitions/Format"
                },
                "drives": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "hasDefensiveStats": {
                    "type": "boolean"
                }
            },
            "required": [
                "$ref",
                "attendance",
                "boxscoreAvailable",
                "boxscoreSource",
                "bracketAvailable",
                "broadcasts",
                "commentaryAvailable",
                "competitors",
                "conferenceCompetition",
                "conversationAvailable",
                "date",
                "dateValid",
                "details",
                "divisionCompetition",
                "drives",
                "format",
                "gameSource",
                "gamecastAvailable",
                "guid",
                "hasDefensiveStats",
                "highlightsAvailable",
                "id",
                "leaders",
                "linescoreSource",
                "lineupAvailable",
                "links",
                "liveAvailable",
                "neutralSite",
                "notes",
                "odds",
                "officials",
                "onWatchESPN",
                "pickcenterAvailable",
                "playByPlayAvailable",
                "playByPlaySource",
                "possessionArrowAvailable",
                "powerIndexes",
                "predictor",
                "previewAvailable",
                "probabilities",
                "recapAvailable",
                "recent",
                "shotChartAvailable",
                "situation",
                "statsSource",
                "status",
                "summaryAvailable",
                "ticketsAvailable",
                "timeValid",
                "timeoutsAvailable",
                "type",
                "uid",
                "venue",
                "wallclockAvailable"
            ],
            "title": "CoreNflEventCompetitionSchema"
        },
        "Source": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "description": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "id",
                "state"
            ],
            "title": "Source"
        },
        "Broadcasts": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Broadcasts"
        },
        "Competitor": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "homeAway": {
                    "type": "string"
                },
                "winner": {
                    "type": "boolean"
                },
                "team": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "score": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "linescores": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "roster": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "statistics": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "leaders": {
                    "$ref": "#/definitions/Broadcasts"
                },
                "record": {
                    "$ref": "#/definitions/Broadcasts"
                }
            },
            "required": [
                "$ref",
                "homeAway",
                "id",
                "leaders",
                "linescores",
                "order",
                "record",
                "roster",
                "score",
                "statistics",
                "team",
                "type",
                "uid",
                "winner"
            ],
            "title": "Competitor"
        },
        "Format": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "regulation": {
                    "$ref": "#/definitions/Overtime"
                },
                "overtime": {
                    "$ref": "#/definitions/Overtime"
                }
            },
            "required": [
                "overtime",
                "regulation"
            ],
            "title": "Format"
        },
        "Overtime": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "periods": {
                    "type": "integer"
                },
                "displayName": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "clock": {
                    "type": "integer"
                }
            },
            "required": [
                "clock",
                "displayName",
                "periods",
                "slug"
            ],
            "title": "Overtime"
        },
        "Link": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "language": {
                    "$ref": "#/definitions/Language"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "href": {
                    "type": "string",
                    "qt-uri-protocols": [
                        "http",
                        "https"
                    ]
                },
                "text": {
                    "type": "string"
                },
                "shortText": {
                    "type": "string"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isPremium": {
                    "type": "boolean"
                }
            },
            "required": [
                "href",
                "isExternal",
                "isPremium",
                "language",
                "rel",
                "shortText",
                "text"
            ],
            "title": "Link"
        },
        "Type": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "text": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "id",
                "slug",
                "text",
                "type"
            ],
            "title": "Type"
        },
        "Venue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "fullName": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/Address"
                },
                "grass": {
                    "type": "boolean"
                },
                "indoor": {
                    "type": "boolean"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Image"
                    }
                }
            },
            "required": [
                "$ref",
                "address",
                "fullName",
                "grass",
                "id",
                "images",
                "indoor"
            ],
            "title": "Venue"
        },
        "Address": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string",
                    "format": "integer"
                },
                "country": {
                    "type": "string"
                }
            },
            "required": [
                "city",
                "country",
                "state",
                "zipCode"
            ],
            "title": "Address"
        },
        "Image": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".jpg"
                    ]
                },
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "alt": {
                    "type": "string"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "alt",
                "height",
                "href",
                "rel",
                "width"
            ],
            "title": "Image"
        },
        "Language": {
            "type": "string",
            "enum": [
                "en-US"
            ],
            "title": "Language"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/core_nfl_event_competition.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417?lang=en&region=us",
  "id": "401547417",
  "guid": "71b7a6e1-d549-32f6-99dc-03f7713496e0",
  "uid": "s:20~l:28~e:401547417~c:401547417",
  "date": "2023-09-17T17:00Z",
  "attendance": 69251,
  "type": {
    "id": "1",
    "text": "Standard",
    "abbreviation": "STD",
    "slug": "standard",
    "type": "standard"
  },
  "timeValid": true,
  "dateValid": true,
  "neutralSite": false,
  "divisionCompetition": false,
  "conferenceCompetition": false,
  "previewAvailable": false,
  "recapAvailable": true,
  "boxscoreAvailable": true,
  "lineupAvailable": false,
  "gamecastAvailable": true,
  "playByPlayAvailable": true,
  "conversationAvailable": true,
  "commentaryAvailable": false,
  "pickcenterAvailable": true,
  "summaryAvailable": true,
  "liveAvailable": false,
  "ticketsAvailable": false,
  "shotChartAvailable": false,
  "timeoutsAvailable": false,
  "possessionArrowAvailable": false,
  "onWatchESPN": false,
  "recent": false,
  "bracketAvailable": false,
  "wallclockAvailable": true,
  "highlightsAvailable": true,
  "gameSource": {
    "id": "1",
    "description": "basic/manual",
    "state": "basic"
  },
  "boxscoreSource": {
    "id": "2",
    "description": "feed",
    "state": "full"
  },
  "playByPlaySource": {
    "id": "2",
    "description": "feed",
    "state": "full"
  },
  "linescoreSource": {
    "id": "1",
    "description": "basic/manual",
    "state": "basic"
  },
  "statsSource": {
    "id": "3",
    "description": "scrubbed",
    "state": "full"
  },
  "venue": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/venues/5348?lang=en&region=us",
    "id": "5348",
    "fullName": "Mercedes-Benz Stadium",
    "address": {
      "city": "Atlanta",
      "state": "GA",
      "zipCode": "30313",
      "country": "USA"
    },
    "grass": false,
    "indoor": true,
    "images": [
      {
        "href": "https://a.espncdn.com/i/venues/nfl/day/interior/5348.jpg",
        "width": 2000,
        "height": 1125,
        "alt": "",
        "rel": [
          "full",
          "day",
          "interior"
        ]
      }
    ]
  },
  "competitors": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1?lang=en&region=us",
      "id": "1",
      "uid": "s:20~l:28~t:1",
      "type": "team",
      "order": 0,
      "homeAway": "home",
      "winner": true,
      "team": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
      },
      "score": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/score?lang=en&region=us"
      },
      "linescores": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/linescores?lang=en&region=us"
      },
      "roster": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster?lang=en&region=us"
      },
      "statistics": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/statistics?lang=en&region=us"
      },
      "leaders": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/leaders?lang=en&region=us"
      },
      "record": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/records?lang=en&region=us"
      }
    },
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9?lang=en&region=us",
      "id": "9",
      "uid": "s:20~l:28~t:9",
      "type": "team",
      "order": 1,
      "homeAway": "away",
      "winner": false,
      "team": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
      },
      "score": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/score?lang=en&region=us"
      },
      "linescores": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/linescores?lang=en&region=us"
      },
      "roster": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster?lang=en&region=us"
      },
      "statistics": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/statistics?lang=en&region=us"
      },
      "leaders": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/leaders?lang=en&region=us"
      },
      "record": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/records?lang=en&region=us"
      }
    }
  ],
  "notes": [],
  "situation": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/situation?lang=en&region=us"
  },
  "status": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/status?lang=en&region=us"
  },
  "odds": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/odds?lang=en&region=us"
  },
  "broadcasts": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/broadcasts?lang=en&region=us"
  },
  "officials": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/officials?lang=en&region=us"
  },
  "details": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/plays?lang=en&region=us"
  },
  "leaders": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/leaders?lang=en&region=us"
  },
  "links": [
    {
      "language": "en-US",
      "rel": [
        "summary",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/game/_/gameId/401547417/packers-falcons",
      "text": "Gamecast",
      "shortText": "Summary",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "summary",
        "sportscenter",
        "app",
        "event"
      ],
      "href": "sportscenter://x-callback-url/showGame?sportName=football&leagueAbbrev=nfl&gameId=401547417",
      "text": "Gamecast",
      "shortText": "Summary",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "now",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/game/_/gameId/401547417",
      "text": "Now",
      "shortText": "Now",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "teamstats",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/matchup?gameId=401547417",
      "text": "Team Stats",
      "shortText": "Team Stats",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "boxscore",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/boxscore/_/gameId/401547417",
      "text": "Box Score",
      "shortText": "Box Score",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "boxscore",
        "sportscenter",
        "app",
        "event"
      ],
      "href": "sportscenter://x-callback-url/showGame?sportName=football&leagueAbbrev=nfl&gameId=401547417",
      "text": "Box Score",
      "shortText": "Box Score",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "gamecast",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/game/_/gameId/401547417",
      "text": "Gamecast",
      "shortText": "Gamecast",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "gamecast",
        "mobile",
        "event"
      ],
      "href": "http://m.espn.com/nfl/gamecast?gameId=401547417&action=summary",
      "text": "Gamecast",
      "shortText": "Gamecast",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "gamecast",
        "sportscenter",
        "app",
        "event"
      ],
      "href": "sportscenter://x-callback-url/showGame?sportName=football&leagueAbbrev=nfl&gameId=401547417",
      "text": "Gamecast",
      "shortText": "Gamecast",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "recap",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/recap?gameId=401547417",
      "text": "Recap",
      "shortText": "Recap",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "pbp",
        "desktop",
        "event"
      ],
      "href": "https://www.espn.com/nfl/playbyplay/_/gameId/401547417",
      "text": "Play-by-Play",
      "shortText": "Play-by-Play",
      "isExternal": false,
