=== aaronweldy/espn-openapi/json_schemas/core_nfl_season_team_2024_12_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CoreNflSeasonTeam2024_12_Schema",
    "definitions": {
        "CoreNflSeasonTeam2024_12_Schema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "guid": {
                    "type": "string",
                    "format": "uuid"
                },
                "uid": {
                    "type": "string"
                },
                "alternateIds": {
                    "$ref": "#/definitions/AlternateIDS"
                },
                "slug": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "alternateColor": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isAllStar": {
                    "type": "boolean"
                },
                "logos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Logo"
                    }
                },
                "record": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "oddsRecords": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "athletes": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "venue": {
                    "$ref": "#/definitions/Venue"
                },
                "groups": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "ranks": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "statistics": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "leaders": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "injuries": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "notes": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "againstTheSpreadRecords": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "franchise": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "projection": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "events": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "transactions": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "coaches": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                },
                "attendance": {
                    "$ref": "#/definitions/AgainstTheSpreadRecords"
                }
            },
            "required": [
                "$ref",
                "abbreviation",
                "againstTheSpreadRecords",
                "alternateColor",
                "alternateIds",
                "athletes",
                "attendance",
                "coaches",
                "color",
                "displayName",
                "events",
                "franchise",
                "groups",
                "guid",
                "id",
                "injuries",
                "isActive",
                "isAllStar",
                "leaders",
                "links",
                "location",
                "logos",
                "name",
                "nickname",
                "notes",
                "oddsRecords",
                "projection",
                "ranks",
                "record",
                "shortDisplayName",
                "slug",
                "statistics",
                "transactions",
                "uid",
                "venue"
            ],
            "title": "CoreNflSeasonTeam2024_12_Schema"
        },
        "AgainstTheSpreadRecords": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "AgainstTheSpreadRecords"
        },
        "AlternateIDS": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sdr": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "sdr"
            ],
            "title": "AlternateIDS"
        },
        "Link": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "language": {
                    "$ref": "#/definitions/Language"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "text": {
                    "type": "string"
                },
                "shortText": {
                    "type": "string"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isPremium": {
                    "type": "boolean"
                }
            },
            "required": [
                "href",
                "isExternal",
                "isPremium",
                "language",
                "rel",
                "shortText",
                "text"
            ],
            "title": "Link"
        },
        "Logo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".jpg",
                        ".png"
                    ]
                },
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "alt": {
                    "type": "string"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastUpdated": {
                    "$ref": "#/definitions/LastUpdated"
                }
            },
            "required": [
                "alt",
                "height",
                "href",
                "rel",
                "width"
            ],
            "title": "Logo"
        },
        "Venue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "fullName": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/Address"
                },
                "grass": {
                    "type": "boolean"
                },
                "indoor": {
                    "type": "boolean"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Logo"
                    }
                }
            },
            "required": [
                "$ref",
                "address",
                "fullName",
                "grass",
                "id",
                "images",
                "indoor"
            ],
            "title": "Venue"
        },
        "Address": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string",
                    "format": "integer"
                },
                "country": {
                    "type": "string"
                }
            },
            "required": [
                "city",
                "country",
                "state",
                "zipCode"
            ],
            "title": "Address"
        },
        "Language": {
            "type": "string",
            "enum": [
                "en-US"
            ],
            "title": "Language"
        },
        "LastUpdated": {
            "type": "string",
            "enum": [
                "2024-06-25T18:51Z",
                "2024-12-03T20:49Z"
            ],
            "title": "LastUpdated"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/core_nfl_season_team_2024_12.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12?lang=en&region=us",
  "id": "12",
  "guid": "f68f2343-8ceb-7a02-740d-af6338be21d2",
  "uid": "s:20~l:28~t:12",
  "alternateIds": {
    "sdr": "8815"
  },
  "slug": "kansas-city-chiefs",
  "location": "Kansas City",
  "name": "Chiefs",
  "nickname": "Chiefs",
  "abbreviation": "KC",
  "displayName": "Kansas City Chiefs",
  "shortDisplayName": "Chiefs",
  "color": "e31837",
  "alternateColor": "ffb612",
  "isActive": true,
  "isAllStar": false,
  "logos": [
    {
      "href": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
      "width": 500,
      "height": 500,
      "alt": "",
      "rel": [
        "full",
        "default"
      ],
      "lastUpdated": "2024-06-25T18:51Z"
    },
    {
      "href": "https://a.espncdn.com/i/teamlogos/nfl/500-dark/kc.png",
      "width": 500,
      "height": 500,
      "alt": "",
      "rel": [
        "full",
        "dark"
      ],
      "lastUpdated": "2024-06-25T18:51Z"
    },
    {
      "href": "https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/kc.png",
      "width": 500,
      "height": 500,
      "alt": "",
      "rel": [
        "full",
        "scoreboard"
      ],
      "lastUpdated": "2024-06-25T18:51Z"
    },
    {
      "href": "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/kc.png",
      "width": 500,
      "height": 500,
      "alt": "",
      "rel": [
        "full",
        "scoreboard",
        "dark"
      ],
      "lastUpdated": "2024-06-25T18:51Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/primary_logo_on_white_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "primary_logo_on_white_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/primary_logo_on_black_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "primary_logo_on_black_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/primary_logo_on_primary_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "primary_logo_on_primary_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/primary_logo_on_secondary_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "primary_logo_on_secondary_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/secondary_logo_on_white_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "secondary_logo_on_white_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/secondary_logo_on_black_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "secondary_logo_on_black_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/secondary_logo_on_primary_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "secondary_logo_on_primary_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    },
    {
      "href": "https://a.espncdn.com/guid/f68f2343-8ceb-7a02-740d-af6338be21d2/logos/secondary_logo_on_secondary_color.png",
      "width": 4096,
      "height": 4096,
      "alt": "",
      "rel": [
        "full",
        "secondary_logo_on_secondary_color"
      ],
      "lastUpdated": "2024-12-03T20:49Z"
    }
  ],
  "record": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/teams/12/record?lang=en&region=us"
  },
  "oddsRecords": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/0/teams/12/odds-records?lang=en&region=us"
  },
  "athletes": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12/athletes?lang=en&region=us"
  },
  "venue": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/venues/3622?lang=en&region=us",
    "id": "3622",
    "fullName": "GEHA Field at Arrowhead Stadium",
    "address": {
      "city": "Kansas City",
      "state": "MO",
      "zipCode": "64129",
      "country": "USA"
    },
    "grass": true,
    "indoor": false,
    "images": [
      {
        "href": "https://a.espncdn.com/i/venues/nfl/day/3622.jpg",
        "width": 2000,
        "height": 1125,
        "alt": "",
        "rel": [
          "full",
          "day"
        ]
      },
      {
        "href": "https://a.espncdn.com/i/venues/nfl/day/interior/3622.jpg",
        "width": 2000,
        "height": 1125,
        "alt": "",
        "rel": [
          "full",
          "day",
          "interior"
        ]
      }
    ]
  },
  "groups": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/6?lang=en&region=us"
  },
  "ranks": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12/ranks?lang=en&region=us"
  },
  "statistics": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/teams/12/statistics?lang=en&region=us"
  },
  "leaders": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/teams/12/leaders?lang=en&region=us"
  },
  "links": [
    {
      "language": "en-US",
      "rel": [
        "clubhouse",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/_/name/kc/kansas-city-chiefs",
      "text": "Clubhouse",
      "shortText": "Clubhouse",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "roster",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/roster/_/name/kc/kansas-city-chiefs",
      "text": "Roster",
      "shortText": "Roster",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "stats",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/stats/_/name/kc/kansas-city-chiefs",
      "text": "Statistics",
      "shortText": "Statistics",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "schedule",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/schedule/_/name/kc",
      "text": "Schedule",
      "shortText": "Schedule",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "photos",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/photos/_/name/kc",
      "text": "photos",
      "shortText": "photos",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "tickets",
        "desktop",
        "team"
      ],
      "href": "https://www.vividseats.com/kansas-city-chiefs-tickets--sports-nfl-football/performer/427?wsUser=717",
      "text": "Tickets",
      "shortText": "Tickets",
      "isExternal": true,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "draftpicks",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/draft/teams/_/name/kc/kansas-city-chiefs",
      "text": "Draft Picks",
      "shortText": "Draft Picks",
      "isExternal": false,
      "isPremium": true
    },
    {
      "language": "en-US",
      "rel": [
        "transactions",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/transactions/_/name/kc",
      "text": "Transactions",
      "shortText": "Transactions",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "injuries",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/injuries/_/name/kc",
      "text": "Injuries",
      "shortText": "Injuries",
      "isExternal": false,
      "isPremium": false
    },
    {
      "language": "en-US",
      "rel": [
        "depthchart",
        "desktop",
        "team"
      ],
      "href": "https://www.espn.com/nfl/team/depth/_/name/kc",
      "text": "Depth Chart",
      "shortText": "Depth Chart",
      "isExternal": false,
      "isPremium": false
    }
  ],
  "injuries": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/teams/12/injuries?lang=en&region=us"
  },
  "notes": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/teams/12/notes?lang=en&region=us"
  },
  "againstTheSpreadRecords": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/teams/12/ats?lang=en&region=us"
  },
  "franchise": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/franchises/12?lang=en&region=us"
  },
  "projection": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12/projection?lang=en&region=us"
  },
  "events": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/12/events?lang=en&region=us"
  },
  "transactions": {
