=== aaronweldy/espn-openapi/json_schemas/fantasy_ffl_news_players_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/FantasyFflNewsPlayersSchema",
    "definitions": {
        "FantasyFflNewsPlayersSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "timestamp": {
                    "type": "string",
                    "format": "date-time"
                },
                "resultsOffset": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "resultsLimit": {
                    "type": "integer"
                },
                "resultsCount": {
                    "type": "integer"
                },
                "feed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Feed"
                    }
                }
            },
            "required": [
                "feed",
                "resultsCount",
                "resultsLimit",
                "resultsOffset",
                "status",
                "timestamp"
            ],
            "title": "FantasyFflNewsPlayersSchema"
        },
        "Feed": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nowId": {
                    "type": "string"
                },
                "contentKey": {
                    "type": "string"
                },
                "dataSourceIdentifier": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "headline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "categorized": {
                    "type": "string",
                    "format": "date-time"
                },
                "lastModified": {
                    "type": "string",
                    "format": "date-time"
                },
                "published": {
                    "type": "string",
                    "format": "date-time"
                },
                "images": {
                    "type": "array",
                    "items": {}
                },
                "story": {
                    "type": "string"
                },
                "premium": {
                    "type": "boolean"
                },
                "links": {
                    "$ref": "#/definitions/Links"
                },
                "allowSearch": {
                    "type": "boolean"
                },
                "allowContentReactions": {
                    "type": "boolean"
                },
                "playerId": {
                    "type": "integer"
                }
            },
            "required": [
                "allowContentReactions",
                "allowSearch",
                "categorized",
                "contentKey",
                "dataSourceIdentifier",
                "description",
                "headline",
                "id",
                "images",
                "lastModified",
                "links",
                "nowId",
                "playerId",
                "premium",
                "published",
                "story",
                "type"
            ],
            "title": "Feed"
        },
        "Links": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mobile": {
                    "$ref": "#/definitions/Mobile"
                },
                "api": {
                    "$ref": "#/definitions/API"
                }
            },
            "required": [
                "api",
                "mobile"
            ],
            "title": "Links"
        },
        "API": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "self": {
                    "$ref": "#/definitions/Self"
                }
            },
            "required": [
                "self"
            ],
            "title": "API"
        },
        "Self": {
            "type": "object",
            "additionalProperties": false,
            "title": "Self"
        },
        "Mobile": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "href"
            ],
            "title": "Mobile"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/fantasy_player_news_3139477_test.json
{
  "feed": [
    {
      "id": 59720628,
      "headline": "Mahomes agreed Wednesday with the Chiefs on a restructure of his contract, Adam Teicher of ESPN.com reports.",
      "description": "Mahomes agreed Wednesday with the Chiefs on a restructure of his contract, Adam Teicher of ESPN.com reports.",
      "story": "Mahomes and star defensive tackle Chris Jones both agreed to restructure their contracts Wednesday, freeing up a total of $49.4 million in cap space to help Kansas City maneuver in free agency. The team has already committed to a handful of key moves, including re-signing wideout Hollywood Brown to a one-year deal, placing the franchise tag on right guard Trey Smith and retaining linebacker Nick Bolton via a three-year contract. Mahomes remains signed through the 2031 season, and he'll enter the 2025 season with a reloaded supporting cast as the Chiefs work to bounce back from a disappointing 40-22 loss to the Eagles in Super Bowl LIX.",
      "published": "2025-03-12T15:55:31+00:00",
      "lastModified": "2025-03-12T15:55:31+00:00",
      "premium": false,
      "type": "Rotowire",
      "playerId": 3139477,
      "nowId": "23-59720628",
      "contentKey": "59720628-23-1-1",
      "dataSourceIdentifier": "a70c50b2a2402",
      "allowContentReactions": false,
      "allowSearch": false,
      "categorized": "2025-03-12T15:55:31Z",
      "images": [],
      "links": {
        "api": {
          "self": {}
        },
        "mobile": {
          "href": "http://m.espn.go.com/wireless/story?storyId=59720628"
        }
      }
    },
    {
      "id": 59659628,
      "headline": "Mahomes completed 21 of 32 pass attempts for 257 yards, three touchdowns and two interceptions while taking four rushing attempts for 25 yards and a lost fumble in Sunday's 40-22 loss to the Eagles in Super Bowl LIX.",
      "description": "Mahomes completed 21 of 32 pass attempts for 257 yards, three touchdowns and two interceptions while taking four rushing attempts for 25 yards and a lost fumble in Sunday's 40-22 loss to the Eagles in Super Bowl LIX.",
      "story": "Mahomes was stifled for nearly three quarters in Super Bowl LIX before completing the first of three garbage-time touchdowns with 34 seconds remaining in the third quarter of Sunday's one-sided affair. The 28-year-old superstar saw his hopes of a potential third consecutive Super Bowl title erode away with each ensuing unsuccessful offensive drive against a ferocious unit led by defensive coordinator Vic Fangio. Mahomes saw a decline in total production in 2024 despite earning the top seed in the AFC, but he maintained a respectable 26:11 TD:INT in 16 starts in the regular season. The Chiefs will look to regroup following a disappointing showing on the national stage and bring in more talent to surround Mahomes for the upcoming 2025 campaign.",
      "published": "2025-02-10T03:45:18+00:00",
      "lastModified": "2025-02-10T03:45:18+00:00",
      "premium": false,
      "type": "Rotowire",
      "playerId": 3139477,
      "nowId": "23-59659628",
      "contentKey": "59659628-23-1-1",
      "dataSourceIdentifier": "7ea143ece9415",
      "allowContentReactions": false,
      "allowSearch": false,
      "categorized": "2025-02-10T03:45:18Z",
      "images": [],
      "links": {
        "api": {
          "self": {}
        },
        "mobile": {
          "href": "http://m.espn.go.com/wireless/story?storyId=59659628"
        }
      }
    }
  ],
  "resultsCount": 2,
  "resultsLimit": 10,
  "resultsOffset": 0,
  "status": "success",
  "timestamp": "2025-06-01T17:16:22+00:00"
}
