=== aaronweldy/espn-openapi/json_schemas/football_nfl_event_athlete_statistics_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/FootballNflEventAthleteStatisticsSchema",
    "definitions": {
        "FootballNflEventAthleteStatisticsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "competition": {
                    "$ref": "#/definitions/Athlete"
                },
                "splits": {
                    "$ref": "#/definitions/Splits"
                },
                "athlete": {
                    "$ref": "#/definitions/Athlete"
                }
            },
            "required": [
                "$ref",
                "athlete",
                "competition",
                "splits"
            ],
            "title": "FootballNflEventAthleteStatisticsSchema"
        },
        "Athlete": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Athlete"
        },
        "Splits": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Category"
                    }
                }
            },
            "required": [
                "abbreviation",
                "categories",
                "id",
                "name"
            ],
            "title": "Splits"
        },
        "Category": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Stat"
                    }
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "name",
                "shortDisplayName",
                "stats",
                "summary"
            ],
            "title": "Category"
        },
        "Stat": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "displayValue": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "description",
                "displayName",
                "displayValue",
                "name",
                "shortDisplayName",
                "value"
            ],
            "title": "Stat"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/competition_401547417_athlete_4426502_statistics_0.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4426502/statistics/0?lang=en&region=us",
  "competition": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417?lang=en&region=us"
  },
  "splits": {
    "id": "0",
    "name": "game",
    "abbreviation": "Game",
    "categories": [
      {
        "name": "general",
        "displayName": "General",
        "stats": [
          {
            "name": "fumbles",
            "value": 0.0,
            "displayName": "Fumbles",
            "shortDisplayName": "F",
            "description": "The number of times a player/team has fumbled the ball",
            "abbreviation": "FUM",
            "displayValue": "0"
          },
          {
            "name": "fumblesLost",
            "value": 0.0,
            "displayName": "Fumbles Lost",
            "shortDisplayName": "FL",
            "description": "The number of times a fumble is recovered by the opposing team",
            "abbreviation": "LST",
            "displayValue": "0"
          },
          {
            "name": "fumblesForced",
            "value": 0.0,
            "displayName": "Forced Fumbles",
            "shortDisplayName": "Forced Fumbles",
            "description": "The total number of forced fumbles.",
            "abbreviation": "FF",
            "displayValue": "0"
          },
          {
            "name": "fumblesRecovered",
            "value": 0.0,
            "displayName": "Fumbles Recovered",
            "shortDisplayName": "FR",
            "description": "The number of fumbles recovered.",
            "abbreviation": "FR",
            "displayValue": "0"
          },
          {
            "name": "fumblesRecoveredYards",
            "value": 0.0,
            "displayName": "Fumbles Recovered Yards",
            "shortDisplayName": "FRYDS",
            "description": "The number of yards gained after a fumble is recovered.",
            "abbreviation": "YDS",
            "displayValue": "0"
          },
          {
            "name": "fumblesTouchdowns",
            "value": 0.0,
            "displayName": "Fumbles Touchdowns",
            "shortDisplayName": "FTD",
            "description": "The number of times a fumbles is recovered and returned for a touchdown.",
            "abbreviation": "FTD",
            "displayValue": "0"
          },
          {
            "name": "gamesPlayed",
            "value": 1.0,
            "displayName": "Games Played",
            "shortDisplayName": "GP",
            "description": "Games Played",
            "abbreviation": "GP",
            "displayValue": "1"
          },
          {
            "name": "offensiveTwoPtReturns",
            "value": 0.0,
            "displayName": "Two Point Returns",
            "shortDisplayName": "2PTR",
            "description": "The number of two point attempts that is returned by the offense.",
            "abbreviation": "2PTR",
            "displayValue": "0"
          },
          {
            "name": "offensiveFumblesTouchdowns",
            "value": 0.0,
            "displayName": "Fumbles Touchdowns",
            "shortDisplayName": "OFTD",
            "description": "The number of times a fumbles is recovered and returned for a touchdown by the offense.",
            "abbreviation": "OFTD",
            "displayValue": "0"
          },
          {
            "name": "defensiveFumblesTouchdowns",
            "value": 0.0,
            "displayName": "Fumbles Touchdowns",
            "shortDisplayName": "DFTD",
            "description": "The number of times a fumbles is recovered and returned for a touchdown by the defense.",
            "abbreviation": "DFTD",
            "displayValue": "0"
          }
        ],
        "shortDisplayName": "General",
        "abbreviation": "gen",
        "summary": ""
      },
      {
        "name": "passing",
        "displayName": "Passing",
        "stats": [
          {
            "name": "avgGain",
            "value": 0.0,
            "displayName": "Average Gain",
            "shortDisplayName": "AG",
            "description": "The average gained yards per position.",
            "abbreviation": "AG",
            "displayValue": "0.0"
          },
          {
            "name": "completionPct",
            "value": 0.0,
            "displayName": "Completion Percentage",
            "shortDisplayName": "CMP%",
            "description": "The percentage of completed passes.",
            "abbreviation": "CMP%",
            "displayValue": "0.0"
          },
          {
            "name": "completions",
            "value": 0.0,
            "displayName": "Completions",
            "shortDisplayName": "CMP",
            "description": "The times a player completes a pass to another player who is eligible to catch a pass.",
            "abbreviation": "CMP",
            "displayValue": "0"
          },
          {
            "name": "ESPNQBRating",
            "value": 0.0,
            "displayName": "ESPN Quarterback Rating",
            "shortDisplayName": "ESPN Quarterback Rating",
            "description": "The quarterback rating used to compare overall offensive performance relative to other positions.",
            "abbreviation": "EQBR",
            "displayValue": "0.0"
          },
          {
            "name": "interceptionPct",
            "value": 0.0,
            "displayName": "Interception Percentage",
            "shortDisplayName": "INT%",
            "description": "The percentage of passes thrown that were intercepted by the opposing team.",
            "abbreviation": "INT%",
            "displayValue": "0.00"
          },
          {
            "name": "interceptions",
            "value": 0.0,
            "displayName": "Interceptions",
            "shortDisplayName": "INT",
            "description": "The number of passes thrown that were intercepted by the opposing team.",
            "abbreviation": "INT",
            "displayValue": "0"
          },
          {
            "name": "longPassing",
            "value": 0.0,
            "displayName": "Longest Pass",
            "shortDisplayName": "LONG",
            "description": "The longest pass play completed in terms of yards.",
            "abbreviation": "LNG",
            "displayValue": "0"
          },
          {
            "name": "miscYards",
            "value": 0.0,
            "displayName": "Miscellaneous Yards",
            "shortDisplayName": "MISC",
            "description": "The number of miscellaneous yards.",
            "abbreviation": "MISC",
            "displayValue": "0"
          },
          {
            "name": "netPassingYards",
            "value": 0.0,
            "displayName": "Net Passing Yards",
            "shortDisplayName": "NYDS",
            "description": "The amount of net passing yards.",
            "abbreviation": "NYDS",
            "displayValue": "0"
          },
          {
            "name": "netPassingYardsPerGame",
            "value": 0.0,
            "displayName": "Net Passing Yards Per Game",
            "shortDisplayName": "NYDS/G",
            "description": "The amount of net passing yards per game.",
            "abbreviation": "NYDS/G",
            "displayValue": "0.0"
          },
          {
            "name": "netTotalYards",
            "value": 0.0,
            "displayName": "Net Total Yards",
            "shortDisplayName": "NTYDS",
            "description": "The amount of net total yards.",
            "abbreviation": "NTYDS",
            "displayValue": "0"
          },
          {
            "name": "netYardsPerGame",
            "value": 0.0,
            "displayName": "Net Yards Per Game",
            "shortDisplayName": "NTYDS/G",
            "description": "The amount of net total yards per game.",
            "abbreviation": "NTYDS/G",
            "displayValue": "0.0"
          },
          {
            "name": "passingAttempts",
            "value": 0.0,
            "displayName": "Passing Attempts",
            "shortDisplayName": "ATT",
            "description": "The number of times a pass is attempted.",
            "abbreviation": "ATT",
            "displayValue": "0"
          },
          {
            "name": "passingBigPlays",
            "value": 0.0,
            "displayName": "Passing Big Plays",
            "shortDisplayName": "BIG",
            "description": "The number of times a pass results in a big play.",
            "abbreviation": "BIGP",
            "displayValue": "0"
          },
          {
            "name": "passingFirstDowns",
            "value": 0.0,
            "displayName": "Passing 1st downs",
            "shortDisplayName": "FIRST",
            "description": "The number of times a pass results in a first down.",
            "abbreviation": "FIRST",
            "displayValue": "0"
          },
          {
            "name": "passingFumbles",
            "value": 0.0,
            "displayName": "Passing Fumbles",
            "shortDisplayName": "F",
            "description": "The number of times the ball has been fumbled after a completed pass.",
            "abbreviation": "FUM",
            "displayValue": "0"
          },
          {
            "name": "passingFumblesLost",
            "value": 0.0,
            "displayName": "Passing Fumbles Lost",
            "shortDisplayName": "FL",
            "description": "The number of times the ball has been fumbled and lost to the opposing team after a completed pass.",
            "abbreviation": "FL",
            "displayValue": "0"
          },
          {
            "name": "passingTouchdownPct",
            "value": 0.0,
            "displayName": "Passing Touchdown %",
            "shortDisplayName": "TD%",
            "description": "The percentage of passes that result in a touchdown.",
            "abbreviation": "TD%",
