=== aaronweldy/espn-openapi/json_schemas/football_nfl_event_401220403_competition_401220403_situation_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/FootballNflEvent401220403_Competition401220403_SituationSchema",
    "definitions": {
        "FootballNflEvent401220403_Competition401220403_SituationSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "lastPlay": {
                    "$ref": "#/definitions/LastPlay"
                },
                "down": {
                    "type": "integer"
                },
                "yardLine": {
                    "type": "integer"
                },
                "distance": {
                    "type": "integer"
                },
                "isRedZone": {
                    "type": "boolean"
                },
                "homeTimeouts": {
                    "type": "integer"
                },
                "awayTimeouts": {
                    "type": "integer"
                }
            },
            "required": [
                "$ref",
                "awayTimeouts",
                "distance",
                "down",
                "homeTimeouts",
                "isRedZone",
                "lastPlay",
                "yardLine"
            ],
            "title": "FootballNflEvent401220403_Competition401220403_SituationSchema"
        },
        "LastPlay": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "LastPlay"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/football_nfl_event_401220403_competition_401220403_situation.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401220403/competitions/401220403/situation?lang=en&region=us",
  "lastPlay": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401220403/competitions/401220403/plays/4012204034370?lang=en&region=us"
  },
  "down": 4,
  "yardLine": 18,
  "distance": 12,
  "isRedZone": false,
  "homeTimeouts": 3,
  "awayTimeouts": 3
}
