=== aaronweldy/espn-openapi/json_schemas/nfl_weekly_qbr_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/NflWeeklyQbrSchema",
    "definitions": {
        "NflWeeklyQbrSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "count": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Item"
                    }
                }
            },
            "required": [
                "$ref",
                "count",
                "items",
                "pageCount",
                "pageIndex",
                "pageSize"
            ],
            "title": "NflWeeklyQbrSchema"
        },
        "Item": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "athlete": {
                    "$ref": "#/definitions/Athlete"
                },
                "team": {
                    "$ref": "#/definitions/Athlete"
                },
                "event": {
                    "$ref": "#/definitions/Athlete"
                },
                "season": {
                    "$ref": "#/definitions/Athlete"
                },
                "splits": {
                    "$ref": "#/definitions/Splits"
                }
            },
            "required": [
                "athlete",
                "event",
                "season",
                "splits",
                "team"
            ],
            "title": "Item"
        },
        "Athlete": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Athlete"
        },
        "Splits": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "$ref": "#/definitions/SplitsName"
                },
                "abbreviation": {
                    "$ref": "#/definitions/SplitsAbbreviation"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Category"
                    }
                }
            },
            "required": [
                "abbreviation",
                "categories",
                "id",
                "name"
            ],
            "title": "Splits"
        },
        "Category": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "$ref": "#/definitions/CategoryName"
                },
                "displayName": {
                    "$ref": "#/definitions/CategoryDisplayName"
                },
                "shortDisplayName": {
                    "$ref": "#/definitions/CategoryDisplayName"
                },
                "abbreviation": {
                    "$ref": "#/definitions/CategoryAbbreviation"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Stat"
                    }
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "name",
                "shortDisplayName",
                "stats"
            ],
            "title": "Category"
        },
        "Stat": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "$ref": "#/definitions/StatName"
                },
                "displayName": {
                    "$ref": "#/definitions/StatDisplayName"
                },
                "shortDisplayName": {
                    "$ref": "#/definitions/StatDisplayName"
                },
                "description": {
                    "type": "string"
                },
                "abbreviation": {
                    "$ref": "#/definitions/StatAbbreviation"
                },
                "value": {
                    "type": "number"
                },
                "displayValue": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "description",
                "displayName",
                "displayValue",
                "name",
                "shortDisplayName",
                "value"
            ],
            "title": "Stat"
        },
        "SplitsAbbreviation": {
            "type": "string",
            "enum": [
                "QBRWeek"
            ],
            "title": "SplitsAbbreviation"
        },
        "CategoryAbbreviation": {
            "type": "string",
            "enum": [
                "GEN"
            ],
            "title": "CategoryAbbreviation"
        },
        "CategoryDisplayName": {
            "type": "string",
            "enum": [
                "General"
            ],
            "title": "CategoryDisplayName"
        },
        "CategoryName": {
            "type": "string",
            "enum": [
                "general"
            ],
            "title": "CategoryName"
        },
        "StatAbbreviation": {
            "type": "string",
            "enum": [
                "PA",
                "PAS",
                "REP",
                "SAC",
                "PEN",
                "TOT",
                "QBP",
                "CWA",
                "QBR",
                "EPE",
                "INT",
                "YAC",
                "RUN",
                "SCR",
                "EXP",
                "FUM",
                "DEF",
                "TQBR",
                "UNQRK"
            ],
            "title": "StatAbbreviation"
        },
        "StatDisplayName": {
            "type": "string",
            "enum": [
                "Points Added",
                "Pass",
                "RUSH EPA",
                "SACK",
                "PENALTY",
                "TOTAL EPA",
                "QB PLAYS",
                "CW AVG",
                "RAW QBR",
                "EXP PASS EPA",
                "INT EPA",
                "YAC EPA",
                "RUN",
                "SCRAM EPA",
                "EXP SACK",
                "FUM EPA",
                "DEF FACED",
                "TOTAL QBR",
                "Unqualified Rank",
                "PTS Added"
            ],
            "title": "StatDisplayName"
        },
        "StatName": {
            "type": "string",
            "enum": [
                "qbpaa",
                "cwepaPassesCondensed",
                "cwepaRushes",
                "cwepaSackedCondensed",
                "cwepaPenalties",
                "cwepaTotal",
                "actionPlays",
                "cwAverage",
                "qbr",
                "cwepaPasses",
                "cwepaInterceptions",
                "cwepaYardsAfterCarry",
                "cwepaRuns",
                "cwepaScrambles",
                "cwepaSacked",
                "cwepaFumbles",
                "avgOppDQBR",
                "schedAdjQBR",
                "unqualifiedRank"
            ],
            "title": "StatName"
        },
        "SplitsName": {
            "type": "string",
            "enum": [
                "QBR Weekly/Game stats"
            ],
            "title": "SplitsName"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/nfl_qbr_week1_2024.json
{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/weeks/1/qbr/10000?lang=en&region=us","count":32,"pageIndex":1,"pageSize":25,"pageCount":2,"items":[{"athlete":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/athletes/8439?lang=en&region=us"},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/20?lang=en&region=us"},"event":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401671696?lang=en&region=us"},"season":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024?lang=en&region=us"},"splits":{"id":"10000","name":"QBR Weekly/Game stats","abbreviation":"QBRWeek","categories":[{"name":"general","displayName":"General","shortDisplayName":"General","abbreviation":"GEN","stats":[{"name":"qbpaa","displayName":"Points Added","shortDisplayName":"PTS Added","description":"Number of points contributed by a quarterback, accounting for QBR and how much he plays, above the level of an average quarterback.","abbreviation":"PA","value":-0.25,"displayValue":"-0.3"},{"name":"cwepaPassesCondensed","displayName":"Pass","shortDisplayName":"Pass","description":"Expected points added on pass attempts with low leverage plays down-weighted.","abbreviation":"PAS","value":1.42,"displayValue":"1.4"},{"name":"cwepaRushes","displayName":"RUSH EPA","shortDisplayName":"RUSH EPA","description":"Expected points added on rushes with low leverage plays down-weighted.","abbreviation":"REP","value":0.0,"displayValue":"0.0"},{"name":"cwepaSackedCondensed","displayName":"SACK","shortDisplayName":"SACK","description":"Expected points added on sacks with low leverage plays down-weighted.","abbreviation":"SAC","value":-0.53,"displayValue":"-0.5"},{"name":"cwepaPenalties","displayName":"PENALTY","shortDisplayName":"PENALTY","description":"Expected points added on penalties with low leverage plays down-weighted.","abbreviation":"PEN","value":0.0,"displayValue":"0.0"},{"name":"cwepaTotal","displayName":"TOTAL EPA","shortDisplayName":"TOTAL EPA","description":"Total expected points added with low leverage plays, according to ESPN Win Probability model, down-weighted.","abbreviation":"TOT","value":1.42,"displayValue":"1.4"},{"name":"actionPlays","displayName":"QB PLAYS","shortDisplayName":"QB PLAYS","description":"Plays on which the QB has a non-zero expected points contribution. Includes most plays that are not handoffs.","abbreviation":"QBP","value":22.0,"displayValue":"22"},{"name":"cwAverage","displayName":"CW AVG","shortDisplayName":"CW AVG","description":"Average clutch weight on QB action plays. Smaller than 1 means QB was in relatively fewer clutch situations; greater than 1 means he was in more.","abbreviation":"CWA","value":0.0,"displayValue":"0.0"},{"name":"qbr","displayName":"RAW QBR","shortDisplayName":"RAW QBR","description":"Raw Total Quarterback Rating, which values quarterback on all play types on a 0-100 scale (not adjusted for opposing defenses faced)","abbreviation":"QBR","value":45.96,"displayValue":"46.0"},{"name":"cwepaPasses","displayName":"EXP PASS EPA","shortDisplayName":"EXP PASS EPA","description":"Clutch-weighted expected points added through completions and incompletions.","abbreviation":"EPE","value":1.42,"displayValue":"1.4"},{"name":"cwepaInterceptions","displayName":"INT EPA","shortDisplayName":"INT EPA","description":"Clutch-weighted expected points added (lost) through interceptions and returns.","abbreviation":"INT","value":0.0,"displayValue":"0.0"},{"name":"cwepaYardsAfterCarry","displayName":"YAC EPA","shortDisplayName":"YAC EPA","description":"Clutch-weighted expected points added (lost) on yards after the catch above/below expectation.","abbreviation":"YAC","value":0.16,"displayValue":"0.2"},{"name":"cwepaRuns","displayName":"RUN","shortDisplayName":"RUN","description":"Clutch-weighted expected points added through rushes","abbreviation":"RUN","value":0.0,"displayValue":"0.0"},{"name":"cwepaScrambles","displayName":"SCRAM EPA","shortDisplayName":"SCRAM EPA","description":"Clutch-weighted expected points added through improvised scrambles.","abbreviation":"SCR","value":0.0,"displayValue":"0.0"},{"name":"cwepaSacked","displayName":"EXP SACK","shortDisplayName":"EXP SACK","description":"Clutch-weighted expected points added (lost) from sacks (not fumbles that may occur because of sacks).","abbreviation":"EXP","value":0.0,"displayValue":"0.0"},{"name":"cwepaFumbles","displayName":"FUM EPA","shortDisplayName":"FUM EPA","description":"Clutch-weighted expected points added (lost) through fumbles, recoveries, and returns.","abbreviation":"FUM","value":0.0,"displayValue":"0.0"},{"name":"avgOppDQBR","displayName":"DEF FACED","shortDisplayName":"DEF FACED","description":"Difficulty of defenses faced.","abbreviation":"DEF","value":56.56,"displayValue":"56.6"},{"name":"schedAdjQBR","displayName":"TOTAL QBR","shortDisplayName":"TOTAL QBR","description":"Adjusted Total Quarterback Rating, which values the quarterback on all play types on a 0-100 scale adjusted for the strength of opposing defenses faced.","abbreviation":"TQBR","value":49.71,"displayValue":"49.7"},{"name":"unqualifiedRank","displayName":"Unqualified Rank","shortDisplayName":"Unqualified Rank","description":"Rank in unqualified QBR list.","abbreviation":"UNQRK","value":18.0,"displayValue":"18"}]}]}},{"athlete":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/athletes/12483?lang=en&region=us"},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/teams/14?lang=en&region=us"},"event":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401671792?lang=en&region=us"},"season":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024?lang=en&region=us"},"splits":{"id":"10000","name":"QBR Weekly/Game stats","abbreviation":"QBRWeek","categories":[{"name":"general","displayName":"General","shortDisplayName":"General","abbreviation":"GEN","stats":[{"name":"qbpaa","displayName":"Points Added","shortDisplayName":"PTS Added","description":"Number of points contributed by a quarterback, accounting for QBR and how much he plays, above the level of an average quarterback.","abbreviation":"PA","value":1.83,"displayValue":"1.8"},{"name":"cwepaPassesCondensed","displayName":"Pass","shortDisplayName":"Pass","description":"Expected points added on pass attempts with low leverage plays down-weighted.","abbreviation":"PAS","value":5.79,"displayValue":"5.8"},{"name":"cwepaRushes","displayName":"RUSH EPA","shortDisplayName":"RUSH EPA","description":"Expected points added on rushes with low leverage plays down-weighted.","abbreviation":"REP","value":0.0,"displayValue":"0.0"},{"name":"cwepaSackedCondensed","displayName":"SACK","shortDisplayName":"SACK","description":"Expected points added on sacks with low leverage plays down-weighted.","abbreviation":"SAC","value":-0.59,"displayValue":"-0.6"},{"name":"cwepaPenalties","displayName":"PENALTY","shortDisplayName":"PENALTY","description":"Expected points added on penalties with low leverage plays down-weighted.","abbreviation":"PEN","value":0.95,"displayValue":"1.0"},{"name":"cwepaTotal","displayName":"TOTAL EPA","shortDisplayName":"TOTAL EPA","description":"Total expected points added with low leverage plays, according to ESPN Win Probability model, down-weighted.","abbreviation":"TOT","value":6.75,"displayValue":"6.8"},{"name":"actionPlays","displayName":"QB PLAYS","shortDisplayName":"QB PLAYS","description":"Plays on which the QB has a non-zero expected points contribution. Includes most plays that are not handoffs.","abbreviation":"QBP","value":56.0,"displayValue":"56"},{"name":"cwAverage","displayName":"CW AVG","shortDisplayName":"CW AVG","description":"Average clutch weight on QB action plays. Smaller than 1 means QB was in relatively fewer clutch situations; greater than 1 means he was in more.","abbreviation":"CWA","value":0.0,"displayValue":"0.0"},{"name":"qbr","displayName":"RAW QBR","shortDisplayName":"RAW QBR","description":"Raw Total Quarterback Rating, which values quarterback on all play types on a 0-100 scale (not adjusted for opposing defenses faced)","abbreviation":"QBR","value":61.4,"displayValue":"61.4"},{"name":"cwepaPasses","displayName":"EXP PASS EPA","shortDisplayName":"EXP PASS EPA","description":"Clutch-weighted expected points added through completions and incompletions.","abbreviation":"EPE","value":5.79,"displayValue":"5.8"},{"name":"cwepaInterceptions","displayName":"INT EPA","shortDisplayName":"INT EPA","description":"Clutch-weighted expected points added (lost) through interceptions and returns.","abbreviation":"INT","value":0.0,"displayValue":"0.0"},{"name":"cwepaYardsAfterCarry","displayName":"YAC EPA","shortDisplayName":"YAC EPA","description":"Clutch-weighted expected points added (lost) on yards after the catch above/below expectation.","abbreviation":"YAC","value":0.02,"displayValue":"0.0"},{"name":"cwepaRuns","displayName":"RUN","shortDisplayName":"RUN","description":"Clutch-weighted expected points added through rushes","abbreviation":"RUN","value":0.0,"displayValue":"0.0"},{"name":"cwepaScrambles","displayName":"SCRAM EPA","shortDisplayName":"SCRAM EPA","description":"Clutch-weighted expected points added through improvised scrambles.","abbreviation":"SCR","value":0.0,"displayValue":"0.0"},{"name":"cwepaSacked","displayName":"EXP SACK","shortDisplayName":"EXP SACK","description":"Clutch-weighted expected points added (lost) from sacks (not fumbles that may occur because of sacks).","abbreviation":"EXP","value":0.0,"displayValue":"0.0"},{"name":"cwepaFumbles","displayName":"FUM EPA","shortDisplayName":"FUM EPA","description":"Clutch-weighted expected points added (lost) through fumbles, recoveries, and returns.","abbreviation":"FUM","value":0.0,"displayValue":"0.0"},{"name":"avgOppDQBR","displayName
