=== aaronweldy/espn-openapi/json_schemas/nfl_leaders_response_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/NflLeadersResponseSchema",
    "definitions": {
        "NflLeadersResponseSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Category"
                    }
                }
            },
            "required": [
                "$ref",
                "abbreviation",
                "categories",
                "id",
                "name",
                "type"
            ],
            "title": "NflLeadersResponseSchema"
        },
        "Category": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "leaders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Leader"
                    }
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "leaders",
                "name",
                "shortDisplayName"
            ],
            "title": "Category"
        },
        "Leader": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "displayValue": {
                    "type": "string",
                    "format": "integer"
                },
                "value": {
                    "type": "number"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Rel"
                    }
                },
                "athlete": {
                    "$ref": "#/definitions/Athlete"
                },
                "team": {
                    "$ref": "#/definitions/Athlete"
                },
                "statistics": {
                    "$ref": "#/definitions/Athlete"
                }
            },
            "required": [
                "athlete",
                "displayValue",
                "rel",
                "statistics",
                "team",
                "value"
            ],
            "title": "Leader"
        },
        "Athlete": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Athlete"
        },
        "Rel": {
            "type": "string",
            "enum": [
                "athlete"
            ],
            "title": "Rel"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/core_nfl_competition_leaders.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/leaders?lang=en&region=us",
  "id": "0",
  "name": "TOTAL",
  "abbreviation": "Any",
  "type": "total",
  "categories": [
    {
      "name": "passingLeader",
      "displayName": "Passing Leader",
      "shortDisplayName": "PASS",
      "abbreviation": "PYDS",
      "leaders": [
        {
          "displayValue": "19/32, 237 YDS, 1 TD, 1 INT",
          "value": 237,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4239086?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4239086/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "14/25, 151 YDS, 3 TD",
          "value": 151,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4036378?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster/4036378/statistics/0?lang=en&region=us"
          }
        }
      ]
    },
    {
      "name": "rushingLeader",
      "displayName": "Rushing Leader",
      "shortDisplayName": "RUSH",
      "abbreviation": "RYDS",
      "leaders": [
        {
          "displayValue": "19 CAR, 124 YDS",
          "value": 124,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4430807?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4430807/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "15 CAR, 55 YDS",
          "value": 55,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4239934?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster/4239934/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "16 CAR, 48 YDS",
          "value": 48,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4373626?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4373626/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "10 CAR, 39 YDS, 1 TD",
          "value": 39,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4239086?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4239086/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "2 CAR, 23 YDS",
          "value": 23,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4036378?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster/4036378/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "3 CAR, 5 YDS",
          "value": 5,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4887558?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster/4887558/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "1 CAR, 1 YDS",
          "value": 1,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4039358?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/9?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/9/roster/4039358/statistics/0?lang=en&region=us"
          }
        }
      ]
    },
    {
      "name": "receivingLeader",
      "displayName": "Receiving Leader",
      "shortDisplayName": "REC",
      "abbreviation": "RECYDS",
      "leaders": [
        {
          "displayValue": "6 REC, 67 YDS, 1 TD",
          "value": 67,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4426502?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4426502/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "3 REC, 60 YDS",
          "value": 60,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/2991662?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/2991662/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "4 REC, 48 YDS",
          "value": 48,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/4430807?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/4430807/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "4 REC, 47 YDS",
          "value": 47,
          "rel": [
            "athlete"
          ],
          "athlete": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/athletes/3054212?lang=en&region=us"
          },
          "team": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/teams/1?lang=en&region=us"
          },
          "statistics": {
            "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/401547417/competitions/401547417/competitors/1/roster/3054212/statistics/0?lang=en&region=us"
          }
        },
        {
          "displayValue": "2 REC, 40 YDS, 1 TD",
          "value": 40,
          "rel": [
            "athlete"
          ],
          "athlete": {
