=== aaronweldy/espn-openapi/json_schemas/nfl_athlete_injury_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/NflAthleteInjurySchema",
    "definitions": {
        "NflAthleteInjurySchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "longComment": {
                    "type": "string"
                },
                "shortComment": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "athlete": {
                    "$ref": "#/definitions/Athlete"
                },
                "team": {
                    "$ref": "#/definitions/Athlete"
                },
                "source": {
                    "$ref": "#/definitions/Source"
                },
                "type": {
                    "$ref": "#/definitions/Type"
                }
            },
            "required": [
                "$ref",
                "athlete",
                "date",
                "id",
                "longComment",
                "shortComment",
                "source",
                "status",
                "team",
                "type"
            ],
            "title": "NflAthleteInjurySchema"
        },
        "Athlete": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Athlete"
        },
        "Source": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "description": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "id",
                "state"
            ],
            "title": "Source"
        },
        "Type": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "description",
                "id",
                "name"
            ],
            "title": "Type"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/nfl_athlete_4426502_injury_598153.json
{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2025/athletes/4426502/injuries/598153?lang=en&region=us","id":"598153","longComment":"The eighth overall pick from the 2022 Draft is now under contract through 2026, although it may not be long before he signs an extension that locks him in beyond that. London had career highs in every major counting stat last year, including 41 more targets (158) and 366 more yards (1,271) than his previous personal bests. He had just three 100-yard performances, but two of those came in the final two games after Michael Penix took over as Atlanta's starting QB. There should be plenty of volume for London again in 2025, after the Falcons focused on their defense this offseason and failed to acquire any significant competition for targets or carries.","shortComment":"The Falcons are exercising their fifth-year option on London's rookie contract, Adam Schefter of ESPN reports.","status":"Active","date":"2025-04-30T14:46Z","athlete":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2025/athletes/4426502?lang=en&region=us"},"team":{"$ref":"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2025/teams/1?lang=en&region=us"},"source":{"id":"1","description":"basic/manual","state":"basic"},"type":{"id":"0","name":"INJURY_STATUS_ACTIVE","description":"active","abbreviation":"A"}}
