=== aaronweldy/espn-openapi/json_schemas/nfl_draft_athlete_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/NflDraftAthleteSchema",
    "definitions": {
        "NflDraftAthleteSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "guid": {
                    "type": "string",
                    "format": "uuid"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "displayWeight": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "displayHeight": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "college": {
                    "$ref": "#/definitions/Athlete"
                },
                "position": {
                    "$ref": "#/definitions/Position"
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Position"
                    }
                },
                "team": {
                    "$ref": "#/definitions/Athlete"
                },
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Attribute"
                    }
                },
                "analysis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Analysis"
                    }
                },
                "pick": {
                    "$ref": "#/definitions/Athlete"
                },
                "athlete": {
                    "$ref": "#/definitions/Athlete"
                },
                "logo": {
                    "$ref": "#/definitions/Logo"
                }
            },
            "required": [
                "$ref",
                "analysis",
                "athlete",
                "attributes",
                "college",
                "displayHeight",
                "displayName",
                "displayWeight",
                "firstName",
                "fullName",
                "guid",
                "height",
                "id",
                "lastName",
                "links",
                "logo",
                "pick",
                "position",
                "positions",
                "shortName",
                "team",
                "weight"
            ],
            "title": "NflDraftAthleteSchema"
        },
        "Analysis": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "type": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                }
            },
            "required": [
                "id",
                "type"
            ],
            "title": "Analysis"
        },
        "Athlete": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Athlete"
        },
        "Attribute": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "displayValue": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "displayValue",
                "name",
                "type",
                "value"
            ],
            "title": "Attribute"
        },
        "Link": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "language": {
                    "type": "string"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "text": {
                    "type": "string"
                },
                "shortText": {
                    "type": "string"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isPremium": {
                    "type": "boolean"
                }
            },
            "required": [
                "href",
                "isExternal",
                "isPremium",
                "language",
                "rel",
                "shortText",
                "text"
            ],
            "title": "Link"
        },
        "Logo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".png"
                    ]
                },
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "alt": {
                    "type": "string"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastUpdated": {
                    "type": "string"
                }
            },
            "required": [
                "alt",
                "height",
                "href",
                "lastUpdated",
                "rel",
                "width"
            ],
            "title": "Logo"
        },
        "Position": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "leaf": {
                    "type": "boolean"
                },
                "parent": {
                    "$ref": "#/definitions/Athlete"
                }
            },
            "required": [
                "$ref",
                "abbreviation",
                "displayName",
                "id",
                "leaf",
                "name",
                "parent"
            ],
            "title": "Position"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/nfl_draft_athlete_response.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/draft/athletes/106308?lang=en&region=us",
  "id": "106308",
  "guid": "975cc6da-01e5-3dcc-8a1a-1c9ecdb27d58",
  "firstName": "Bryce",
  "lastName": "Young",
  "fullName": "Bryce Young",
  "displayName": "Bryce Young",
  "shortName": "B. Young",
  "weight": 204.0,
  "displayWeight": "204 lbs",
  "height": 70.125,
  "displayHeight": "5' 10\"",
  "links": [
    {
      "language": "en-US",
      "shortText": "Player Card",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/_/id/4685720/bryce-young",
      "rel": [
        "playercard",
        "desktop",
        "athlete"
      ],
      "text": "Player Card"
    },
    {
      "language": "en-US",
      "shortText": "Stats",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/stats/_/id/4685720/bryce-young",
      "rel": [
        "stats",
        "desktop",
        "athlete"
      ],
      "text": "Stats"
    },
    {
      "language": "en-US",
      "shortText": "Splits",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/splits/_/id/4685720/bryce-young",
      "rel": [
        "splits",
        "desktop",
        "athlete"
      ],
      "text": "Splits"
    },
    {
      "language": "en-US",
      "shortText": "Game Log",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/gamelog/_/id/4685720/bryce-young",
      "rel": [
        "gamelog",
        "desktop",
        "athlete"
      ],
      "text": "Game Log"
    },
    {
      "language": "en-US",
      "shortText": "News",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/news/_/id/4685720/bryce-young",
      "rel": [
        "news",
        "desktop",
        "athlete"
      ],
      "text": "News"
    },
    {
      "language": "en-US",
      "shortText": "Bio",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/bio/_/id/4685720/bryce-young",
      "rel": [
        "bio",
        "desktop",
        "athlete"
      ],
      "text": "Bio"
    },
    {
      "language": "en-US",
      "shortText": "Overview",
      "isExternal": false,
      "isPremium": false,
      "href": "https://www.espn.com/nfl/player/_/id/4685720/bryce-young",
      "rel": [
        "overview",
        "desktop",
        "athlete"
      ],
      "text": "Overview"
    }
  ],
  "college": {
    "$ref": "http://sports.core.api.espn.com/v2/colleges/333?lang=en&region=us"
  },
  "position": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/8?lang=en&region=us",
    "parent": {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/70?lang=en&region=us"
    },
    "id": "8",
    "name": "Quarterback",
    "abbreviation": "QB",
    "displayName": "Quarterback",
    "leaf": true
  },
  "positions": [
    {
      "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/8?lang=en&region=us",
      "parent": {
        "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/positions/70?lang=en&region=us"
      },
      "id": "8",
      "name": "Quarterback",
      "abbreviation": "QB",
      "displayName": "Quarterback",
      "leaf": true
    }
  ],
  "team": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/college-football/seasons/2022/teams/333?lang=en&region=us"
  },
  "attributes": [
    {
      "type": 4,
      "name": "speed",
      "displayName": "Speed",
      "abbreviation": "SPD",
      "value": 0.0,
      "displayValue": "0"
    },
    {
      "type": 2,
      "name": "grade",
      "displayName": "Grade",
      "abbreviation": "GRADE",
      "value": 96.0,
      "displayValue": "96"
    },
    {
      "type": 6,
      "name": "hand",
      "displayName": "Hand",
      "abbreviation": "HAND",
      "value": 9.75,
      "displayValue": "9.75"
    },
    {
      "type": 1,
      "name": "overall",
      "displayName": "Overall",
      "abbreviation": "OVR RK",
      "value": 1.0,
      "displayValue": "1"
    },
    {
      "type": 3,
      "name": "rank",
      "displayName": "Rank",
      "abbreviation": "POS RK",
      "value": 1.0,
      "displayValue": "1"
    },
    {
      "type": 5,
      "name": "arm",
      "displayName": "Arm",
      "abbreviation": "ARM",
      "value": 30.5,
      "displayValue": "30.5"
    }
  ],
  "analysis": [
    {
      "id": "10",
      "type": "bottomline",
      "text": "Young has a short, linear frame by NFL quarterback standards and weighed in at 204 pounds at the combine. That means durability is his biggest concern entering the NFL. But as a passer, Young is a fast processor who has rare poise. The game slows down for him, and he never seems to panic. He is sudden and tough in the pocket, with quick feet and a swift release. Young displays very good ball placement on the perimeter at all three levels, and he showcases excellent touch and knows how to lead receivers into yards after the catch. He does need to improve the consistency of his accuracy on anticipation throws over the middle of the field. But Young shows great overall operational poise, and no moment is too big for him. He's a pocket passer first, but he has the mobility to frequently extend plays and generate production with his feet. <i>-- Final evaluation</i>"
    },
    {
      "id": "11",
      "type": "video",
      "text": "35983700"
    },
    {
      "id": "8",
      "type": "predraft",
      "text": "Young is a fast processor with a quick release and the touch to lead receivers to yards after the catch. He has rare poise, no moment is too big for him and he rarely makes mental errors. He's a pocket passer first, but Young has the mobility to extend plays and effectively run or scramble. He has held up well except for a shoulder injury that limited him for a few weeks in the middle of the 2022 season, even though he has a short linear frame by NFL quarterback standards. <i>-- Steve Muench</i><br><br><b>Matt Miller's NFL comp:</b> <a href=\"https://www.espn.com/nfl/player/_/id/2580/drew-brees\" target=\"_blank\">Drew Brees</a> <style>div.draftTable__content > p > a{color:#06c !important; border-bottom:1px dotted #06c !important}div.draftTable__content > p > a:hover{opacity:.8 !important; border-bottom:1px solid #06c !important}</style><br><br><b>Read:</b> <a href=\"https://www.espn.com/nfl/draft2023/story/_/id/36275794/2023-nfl-draft-bryce-young-biggest-question-carolina-panthers\" target=\"_new\">Can Young be the NFL's exception? </a> <style>div.draftTable__content > p > a{color:#06c !important; border-bottom:1px dotted #06c !important}div.draftTable__content > p > a:hover{opacity:.8 !important; border-bottom:1px solid #06c !important}</style>"
    },
    {
      "id": "9",
      "type": "postdraft",
      "text": "Young's skill set is an ideal fit in Frank Reich's offense, which mixes a passing game that attacks multiple areas of the field with a diverse run game. New coordinator Thomas Brown comes from a Rams scheme that uses shifts and motions to create confusion, and Young's accuracy, decision-making and poise should translate well here. He could be the long-term answer for the Panthers, who completed just 58.4% of their passes and finished 31st in Total QBR at 27.6 last season. <i>-- Jordan Reid</i><br><br><b>Projected Year 1 impact:</b> Rookie of the Year candidate. The Panthers made the big move to trade up to select Young, so they won't wait to get him onto the field. His composure under center, field vision, ability to extend the play and full-field accuracy will allow him to start -- and produce -- immediately as a pro. <i>-- Miller</i><br><br><b>Read:</b> <a href=\"https://www.espn.com/nfl/story/_/id/36307374/carolina-panthers-take-bryce-young-no-1-pick-nfl-draft\" target=\"_blank\">Panthers take QB Young at No. 1 overall</a> <style>div.draftTable__content > p > a{color:#06c !important; border-bottom:1px dotted #06c !important}div.draftTable__content > p > a:hover{opacity:.8 !important; border-bottom:1px solid #06c !important}</style><br><br><b>More from David Newton:</b> <a href=\"https://www.espn.com/blog/carolina-panthers/post/_/id/37615/carolina-panthers-nfl-draft-picks-2023-analysis-for-every-selection\" target=\"_blank\">Analysis of every Panthers pick</a> <style>div.draftTable__content > p > a{color:#06c !important; border-bottom:1px dotted #06c !important}div.draftTable__content > p > a:hover{opacity:.8 !important; border-bottom:1px solid #06c !important}</style>"
    },
    {
      "id": "7",
      "type": "production",
      "grade": 1
    },
    {
      "id": "17",
      "type": "hws",
      "grade": 4
    },
    {
      "id": "5",
      "type": "durability",
      "grade": 3
    },
    {
      "id": "6",
      "type": "character",
      "grade": 1
    },
    {
      "id": "12",
      "type": "trait1",
      "grade": 1
    },
    {
      "id": "13",
      "type": "trait2",
      "grade": 2
    },
    {
      "id": "14",
      "type": "trait3",
      "grade": 2
    },
    {
      "id": "15",
      "type": "trait4",
      "grade": 1
    }
  ],
  "pick": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2023/draft/rounds/1/picks/1?lang=en&region=us"
  },
  "athlete": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/college-football/athletes/4685720?lang=en&region=us"
  },
  "logo": {
    "href": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
    "width": 500,
    "height": 500,
    "alt": "",
    "rel": [
      "full",
      "default"
    ],
    "lastUpdated": "2022-08-30T21:52:00+00:00"
  }
}
