=== aaronweldy/espn-openapi/json_schemas/site_web_api_season_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SiteWebAPISeasonSchema",
    "definitions": {
        "SiteWebAPISeasonSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "year": {
                    "type": "integer"
                },
                "displayName": {
                    "type": "string",
                    "format": "integer"
                },
                "startDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "endDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Type"
                    }
                }
            },
            "required": [
                "displayName",
                "endDate",
                "startDate",
                "types",
                "year"
            ],
            "title": "SiteWebAPISeasonSchema"
        },
        "Type": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "endDate": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "endDate",
                "id",
                "name",
                "startDate",
                "type"
            ],
            "title": "Type"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/site_web_api_wnba_season.json
{"year":2025,"displayName":"2025","startDate":"2025-04-14T07:00:00.000+00:00","endDate":"2025-10-20T06:59:00.000+00:00","types":[{"id":"1","type":1,"name":"Preseason","startDate":"2025-04-14T07:00:00.000+00:00","endDate":"2025-05-15T06:59:00.000+00:00"},{"id":"2","type":2,"name":"Regular Season","startDate":"2025-05-15T07:00:00.000+00:00","endDate":"2025-09-12T06:59:00.000+00:00"},{"id":"3","type":3,"name":"Postseason","startDate":"2025-09-12T07:00:00.000+00:00","endDate":"2025-10-20T06:59:00.000+00:00"},{"id":"4","type":4,"name":"Off Season","startDate":"2025-10-20T07:00:00.000+00:00","endDate":"2026-05-01T06:59:00.000+00:00"}]}

=== aaronweldy/espn-openapi/json_output/site_web_api_college_baseball_season.json
{"year":2025,"displayName":"2024-25","startDate":"2024-07-06T04:00:00.000+00:00","endDate":"2025-06-30T03:59:00.000+00:00","types":[{"id":"1","type":1,"name":"Preseason","startDate":"2024-07-06T04:00:00.000+00:00","endDate":"2025-01-10T04:59:00.000+00:00"},{"id":"2","type":2,"name":"Regular Season","startDate":"2025-01-10T05:00:00.000+00:00","endDate":"2025-05-29T03:59:00.000+00:00"},{"id":"3","type":3,"name":"Regionals","startDate":"2025-05-29T04:00:00.000+00:00","endDate":"2025-06-05T03:59:00.000+00:00"},{"id":"4","type":4,"name":"Super Regionals","startDate":"2025-06-05T04:00:00.000+00:00","endDate":"2025-06-10T03:59:00.000+00:00"},{"id":"5","type":5,"name":"World Series","startDate":"2025-06-10T04:00:00.000+00:00","endDate":"2025-06-20T03:59:00.000+00:00"},{"id":"6","type":6,"name":"Championship Series","startDate":"2025-06-20T04:00:00.000+00:00","endDate":"2025-06-30T03:59:00.000+00:00"}]}
