=== aaronweldy/espn-openapi/json_schemas/soccer_standings_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SoccerStandingsSchema",
    "definitions": {
        "SoccerStandingsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "uid": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Child"
                    }
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Season"
                    }
                }
            },
            "required": [
                "abbreviation",
                "children",
                "id",
                "name",
                "seasons",
                "uid"
            ],
            "title": "SoccerStandingsSchema"
        },
        "Child": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "uid": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "standings": {
                    "$ref": "#/definitions/Standings"
                }
            },
            "required": [
                "abbreviation",
                "id",
                "name",
                "standings",
                "uid"
            ],
            "title": "Child"
        },
        "Standings": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "$ref": "#/definitions/Name"
                },
                "displayName": {
                    "$ref": "#/definitions/DisplayName"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "season": {
                    "type": "integer"
                },
                "seasonType": {
                    "type": "integer"
                },
                "seasonDisplayName": {
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Entry"
                    }
                }
            },
            "required": [
                "displayName",
                "entries",
                "id",
                "links",
                "name",
                "season",
                "seasonDisplayName",
                "seasonType"
            ],
            "title": "Standings"
        },
        "Entry": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "team": {
                    "$ref": "#/definitions/Team"
                },
                "note": {
                    "$ref": "#/definitions/Note"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Stat"
                    }
                }
            },
            "required": [
                "stats",
                "team"
            ],
            "title": "Entry"
        },
        "Note": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                }
            },
            "required": [
                "color",
                "description",
                "rank"
            ],
            "title": "Note"
        },
        "Stat": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "$ref": "#/definitions/Name"
                },
                "displayName": {
                    "$ref": "#/definitions/Description"
                },
                "shortDisplayName": {
                    "$ref": "#/definitions/ShortDisplayName"
                },
                "description": {
                    "$ref": "#/definitions/Description"
                },
                "abbreviation": {
                    "$ref": "#/definitions/Abbreviation"
                },
                "type": {
                    "$ref": "#/definitions/TypeEnum"
                },
                "value": {
                    "type": "number"
                },
                "displayValue": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "summary": {
                    "type": "string"
                }
            },
            "required": [
                "abbreviation",
                "description",
                "displayName",
                "displayValue",
                "name",
                "shortDisplayName",
                "type"
            ],
            "title": "Stat"
        },
        "Team": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "shortDisplayName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "logos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Logo"
                    }
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "isNational": {
                    "type": "boolean"
                }
            },
            "required": [
                "abbreviation",
                "displayName",
                "id",
                "isActive",
                "isNational",
                "links",
                "location",
                "logos",
                "name",
                "shortDisplayName",
                "uid"
            ],
            "title": "Team"
        },
        "Link": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "language": {
                    "$ref": "#/definitions/Language"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LinkRel"
                    }
                },
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".1"
                    ]
                },
                "text": {
                    "$ref": "#/definitions/Text"
                },
                "shortText": {
                    "$ref": "#/definitions/DisplayName"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isPremium": {
                    "type": "boolean"
                }
            },
            "required": [
                "href",
                "isExternal",
                "isPremium",
                "language",
                "rel",
                "shortText",
                "text"
            ],
            "title": "Link"
        },
        "Logo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "href": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ],
                    "qt-uri-extensions": [
                        ".png"
                    ]
                },
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "alt": {
                    "type": "string"
                },
                "rel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LogoRel"
                    }
                },
                "lastUpdated": {
                    "$ref": "#/definitions/LastUpdated"
                }
            },
            "required": [
                "alt",
                "height",
                "href",
                "lastUpdated",
                "rel",
                "width"
            ],
            "title": "Logo"
        },
        "Season": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "year": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TypeElement"
                    }
                }
            },
            "required": [
                "displayName",
                "endDate",
                "startDate",
                "types",
                "year"
            ],
            "title": "Season"
        },
        "TypeElement": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "hasStandings": {
                    "type": "boolean"
                }
            },
            "required": [
                "abbreviation",
                "endDate",
                "hasStandings",
                "id",
                "name",
                "startDate"
            ],
            "title": "TypeElement"
        },
        "DisplayName": {
            "type": "string",
            "enum": [
                "Clubhouse",
                "Standings"
            ],
            "title": "DisplayName"
        },
        "Abbreviation": {
            "type": "string",
            "enum": [
                "GP",
                "L",
                "GD",
                "P",
                "A",
                "F",
                "D",
                "W",
                "PD",
                "PPG",
                "R",
                "RC",
                "Total"
            ],
            "title": "Abbreviation"
        },
        "Description": {
            "type": "string",
            "enum": [
                "Games Played",
                "Losses",
                "Goal Difference",
                "Points",
                "Goals Against",
                "Goals For",
                "Draws",
                "Wins",
                "Point Deductions",
                "Points Per Game",
                "Rank",
                "Rank Change",
                "Overall Record",
                "Overall"
            ],
            "title": "Description"
        },
        "Name": {
            "type": "string",
            "enum": [
                "gamesPlayed",
                "losses",
                "pointDifferential",
                "points",
                "pointsAgainst",
                "pointsFor",
                "ties",
                "wins",
                "deductions",
                "ppg",
                "rank",
                "rankChange",
                "overall"
            ],
            "title": "Name"
        },
        "ShortDisplayName": {
            "type": "string",
            "enum": [
                "GP",
                "L",
                "GD",
                "P",
                "A",
                "F",
                "D",
                "W",
                "Deductions",
                "PPG",
                "Rank",
                "Rank Change",
                "OVER"
            ],
            "title": "ShortDisplayName"
        },
        "TypeEnum": {
            "type": "string",
            "enum": [
                "gamesplayed",
                "losses",
                "pointdifferential",
                "points",
                "pointsagainst",
                "pointsfor",
                "ties",
                "wins",
                "deductions",
                "ppg",
                "rank",
                "rankchange",
                "total"
            ],
            "title": "TypeEnum"
        },
        "Language": {
            "type": "string",
            "enum": [
                "en-US"
            ],
            "title": "Language"
        },
        "LinkRel": {
            "type": "string",
            "enum": [
                "clubhouse",
                "desktop",
                "team",
                "standings"
            ],
            "title": "LinkRel"
        },
        "Text": {
            "type": "string",
            "enum": [
                "Clubhouse",
                "Full Table"
            ],
            "title": "Text"
        },
        "LastUpdated": {
            "type": "string",
            "enum": [
                "2024-01-04T17:49Z",
                "2019-05-08T16:07Z",
                "2025-03-21T13:31Z",
                "2020-07-16T16:13Z"
            ],
            "title": "LastUpdated"
        },
        "LogoRel": {
            "type": "string",
            "enum": [
                "full",
                "default"
            ],
            "title": "LogoRel"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/soccer_ger_1_standings.json
{
  "id": "10",
  "name": "German Bundesliga",
  "abbreviation": "Bundesliga",
  "children": [
    {
      "id": "1",
      "name": "2024-25 German Bundesliga",
      "abbreviation": "2024-25",
      "standings": {
        "season": 2024,
        "seasonType": 1,
        "entries": [
          {
            "note": {
              "color": "#81D6AC",
              "description": "Champions League",
              "rank": 1
            },
            "team": {
              "isNational": false,
              "id": "132",
              "uid": "s:600~t:132",
              "location": "Bayern Munich",
              "name": "Bayern Munich",
              "abbreviation": "MUN",
              "displayName": "Bayern Munich",
              "shortDisplayName": "Bayern",
              "isActive": true,
              "logos": [
                {
                  "lastUpdated": "2022-07-27T14:42Z",
                  "href": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
                  "width": 500,
                  "height": 500,
                  "alt": "",
                  "rel": [
                    "full",
                    "default"
                  ]
                }
              ],
              "links": [
                {
                  "language": "en-US",
                  "shortText": "Clubhouse",
                  "href": "https://www.espn.com/soccer/club/_/id/132/bayern-munich",
                  "text": "Clubhouse",
                  "rel": [
                    "clubhouse",
                    "desktop",
                    "team"
                  ],
                  "isExternal": false,
                  "isPremium": false
                }
              ]
            },
            "stats": [
              {
                "name": "gamesPlayed",
                "type": "gamesplayed",
                "displayName": "Games Played",
                "shortDisplayName": "GP",
                "description": "Games Played",
                "abbreviation": "GP",
                "value": 34.0,
                "displayValue": "34"
              },
              {
                "name": "losses",
                "type": "losses",
                "displayName": "Losses",
                "shortDisplayName": "L",
                "description": "Losses",
                "abbreviation": "L",
                "value": 2.0,
                "displayValue": "2"
              },
              {
                "name": "pointDifferential",
                "type": "pointdifferential",
                "displayName": "Goal Difference",
                "shortDisplayName": "GD",
                "description": "Goal Difference",
                "abbreviation": "GD",
                "value": 67.0,
                "displayValue": "+67"
              },
              {
                "name": "points",
                "type": "points",
                "displayName": "Points",
                "shortDisplayName": "P",
                "description": "Points",
                "abbreviation": "P",
                "value": 82.0,
                "displayValue": "82"
              },
              {
                "name": "pointsAgainst",
                "type": "pointsagainst",
                "displayName": "Goals Against",
                "shortDisplayName": "A",
                "description": "Goals Against",
                "abbreviation": "A",
                "value": 32.0,
                "displayValue": "32"
              },
              {
                "name": "pointsFor",
                "type": "pointsfor",
                "displayName": "Goals For",
                "shortDisplayName": "F",
                "description": "Goals For",
                "abbreviation": "F",
                "value": 99.0,
                "displayValue": "99"
              },
              {
                "name": "ties",
                "type": "ties",
                "displayName": "Draws",
                "shortDisplayName": "D",
                "description": "Draws",
                "abbreviation": "D",
                "value": 7.0,
                "displayValue": "7"
              },
              {
                "name": "wins",
                "type": "wins",
                "displayName": "Wins",
                "shortDisplayName": "W",
                "description": "Wins",
                "abbreviation": "W",
                "value": 25.0,
                "displayValue": "25"
              },
              {
                "name": "deductions",
                "type": "deductions",
                "displayName": "Point Deductions",
                "shortDisplayName": "Deductions",
                "description": "Point Deductions",
                "abbreviation": "PD",
                "value": 0.0,
                "displayValue": ""
              },
              {
                "name": "ppg",
                "type": "ppg",
                "displayName": "Points Per Game",
                "shortDisplayName": "PPG",
                "description": "Points Per Game",
                "abbreviation": "PPG",
                "value": 0.0,
                "displayValue": "0"
              },
              {
                "name": "rank",
                "type": "rank",
                "displayName": "Rank",
                "shortDisplayName": "Rank",
                "description": "Rank",
                "abbreviation": "R",
                "value": 1.0,
                "displayValue": "1"
              },
              {
                "name": "rankChange",
                "type": "rankchange",
                "displayName": "Rank Change",
                "shortDisplayName": "Rank Change",
                "description": "Rank Change",
                "abbreviation": "RC",
                "value": 0.0,
                "displayValue": "0"
              },
              {
                "id": "0",
                "summary": "25-7-2",
                "name": "overall",
                "type": "total",
                "displayName": "Overall",
                "shortDisplayName": "OVER",
                "description": "Overall Record",
                "abbreviation": "Total",
                "displayValue": "25-7-2"
              }
            ]
          },
          {
            "note": {
              "color": "#81D6AC",
              "description": "Champions League",
              "rank": 2
            },
            "team": {
              "isNational": false,
              "id": "131",
              "uid": "s:600~t:131",
              "location": "Bayer Leverkusen",
              "name": "Bayer Leverkusen",
              "abbreviation": "B04",
              "displayName": "Bayer Leverkusen",
              "shortDisplayName": "Leverkusen",
              "isActive": true,
              "logos": [
                {
                  "lastUpdated": "2024-01-04T17:49Z",
                  "href": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
                  "width": 500,
                  "height": 500,
                  "alt": "",
                  "rel": [
                    "full",
                    "default"
                  ]
                }
              ],
              "links": [
                {
                  "language": "en-US",
                  "shortText": "Clubhouse",
                  "href": "https://www.espn.com/soccer/club/_/id/131/bayer-leverkusen",
                  "text": "Clubhouse",
                  "rel": [
                    "clubhouse",
                    "desktop",
                    "team"
                  ],
                  "isExternal": false,
                  "isPremium": false
                }
              ]
            },
            "stats": [
              {
                "name": "gamesPlayed",
                "type": "gamesplayed",
                "displayName": "Games Played",
                "shortDisplayName": "GP",
                "description": "Games Played",
                "abbreviation": "GP",
                "value": 34.0,
                "displayValue": "34"
              },
              {
                "name": "losses",
                "type": "losses",
                "displayName": "Losses",
                "shortDisplayName": "L",
                "description": "Losses",
                "abbreviation": "L",
                "value": 3.0,
                "displayValue": "3"
              },
              {
                "name": "pointDifferential",
                "type": "pointdifferential",
                "displayName": "Goal Difference",
                "shortDisplayName": "GD",
                "description": "Goal Difference",
                "abbreviation": "GD",
                "value": 29.0,
                "displayValue": "+29"
              },
              {
                "name": "points",
                "type": "points",
                "displayName": "Points",
                "shortDisplayName": "P",
                "description": "Points",
                "abbreviation": "P",
                "value": 69.0,
                "displayValue": "69"
              },
              {
                "name": "pointsAgainst",
                "type": "pointsagainst",
                "displayName": "Goals Against",
                "shortDisplayName": "A",
                "description": "Goals Against",
                "abbreviation": "A",
                "value": 43.0,
                "displayValue": "43"
              },
              {
                "name": "pointsFor",
                "type": "pointsfor",
                "displayName": "Goals For",
                "shortDisplayName": "F",
                "description": "Goals For",
                "abbreviation": "F",
                "value": 72.0,
                "displayValue": "72"
              },
              {
                "name": "ties",
                "type": "ties",
                "displayName": "Draws",
                "shortDisplayName": "D",
