=== aaronweldy/espn-openapi/json_schemas/sports_core_group_details_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SportsCoreGroupDetailsSchema",
    "definitions": {
        "SportsCoreGroupDetailsSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                },
                "uid": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "abbreviation": {
                    "type": "string"
                },
                "season": {
                    "$ref": "#/definitions/Children"
                },
                "children": {
                    "$ref": "#/definitions/Children"
                },
                "parent": {
                    "$ref": "#/definitions/Children"
                },
                "standings": {
                    "$ref": "#/definitions/Children"
                },
                "isConference": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "teams": {
                    "$ref": "#/definitions/Children"
                }
            },
            "required": [
                "$ref",
                "abbreviation",
                "children",
                "id",
                "isConference",
                "name",
                "parent",
                "season",
                "slug",
                "standings",
                "teams",
                "uid"
            ],
            "title": "SportsCoreGroupDetailsSchema"
        },
        "Children": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "http"
                    ]
                }
            },
            "required": [
                "$ref"
            ],
            "title": "Children"
        }
    }
}

=== aaronweldy/espn-openapi/json_output/sports_core_group_details_afc.json
{
  "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/8?lang=en&region=us",
  "uid": "s:20~l:28~g:8",
  "id": "8",
  "name": "American Football Conference",
  "abbreviation": "AFC",
  "season": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024?lang=en&region=us"
  },
  "children": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/8/children?lang=en&region=us"
  },
  "parent": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/9?lang=en&region=us"
  },
  "standings": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/8/standings?lang=en&region=us"
  },
  "isConference": true,
  "slug": "american-football-conference",
  "teams": {
    "$ref": "http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/2024/types/2/groups/8/teams?lang=en&region=us"
  }
}
